/*
 Copyright (C) 2026 JQuantLib migration contributors.
 Tests for BatesProcess (Phase 5h.5-Bates).
 */
package org.jquantlib.testsuite.processes;

import org.jquantlib.Settings;
import org.jquantlib.daycounters.Actual365Fixed;
import org.jquantlib.math.matrixutilities.Array;
import org.jquantlib.processes.BatesProcess;
import org.jquantlib.quotes.Handle;
import org.jquantlib.quotes.Quote;
import org.jquantlib.quotes.SimpleQuote;
import org.jquantlib.termstructures.YieldTermStructure;
import org.jquantlib.termstructures.yieldcurves.FlatForward;
import org.jquantlib.testsuite.util.ReferenceReader;
import org.jquantlib.testsuite.util.ReferenceReader.Case;
import org.jquantlib.testsuite.util.Tolerance;
import org.jquantlib.time.Date;
import org.jquantlib.time.Month;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

/**
 * Cross-validated tests for {@link BatesProcess#drift},
 * {@link BatesProcess#evolve}, and the lambda/nu/delta/factors accessors.
 * Reference values from
 * {@code migration-harness/references/processes/bates_process.json}
 * generated by {@code bates_process_probe} against C++ v1.42.1.
 */
public class BatesProcessTest {

    @Test public void drift_midV0()       { runDriftCase("drift_midV0"); }
    @Test public void drift_lowV0()       { runDriftCase("drift_lowV0"); }
    @Test public void drift_zeroLambda()  { runDriftCase("drift_zeroLambda"); }

    @Test public void evolve_midV0()      { runEvolveCase("evolve_midV0"); }
    @Test public void evolve_tinyJump()   { runEvolveCase("evolve_tinyJump"); }
    @Test public void evolve_strongJump() { runEvolveCase("evolve_strongJump"); }

    private static BatesProcess makeProcess(final JSONObject in) {
        final double r      = in.getDouble("r");
        final double q      = in.getDouble("q");
        final double s0     = in.getDouble("s0");
        final double v0     = in.getDouble("v0");
        final double kappa  = in.getDouble("kappa");
        final double theta  = in.getDouble("theta");
        final double sigma  = in.getDouble("sigma");
        final double rho    = in.getDouble("rho");
        final double lambda = in.getDouble("lambda");
        final double nu     = in.getDouble("nu");
        final double delta  = in.getDouble("delta");

        final Date today = new Date(22, Month.April, 2026);
        new Settings().setEvaluationDate(today);

        final YieldTermStructure rCurve = new FlatForward(today,
                new Handle<Quote>(new SimpleQuote(r)), new Actual365Fixed());
        final YieldTermStructure qCurve = new FlatForward(today,
                new Handle<Quote>(new SimpleQuote(q)), new Actual365Fixed());
        final Handle<Quote> spot = new Handle<Quote>(new SimpleQuote(s0));

        final BatesProcess process = new BatesProcess(
                new Handle<YieldTermStructure>(rCurve),
                new Handle<YieldTermStructure>(qCurve),
                spot, v0, kappa, theta, sigma, rho, lambda, nu, delta);
        process.update();
        return process;
    }

    private static void runDriftCase(final String name) {
        final ReferenceReader reader = ReferenceReader.load("processes/bates_process");
        final Case c = reader.getCase(name);
        final JSONObject in = c.inputs();

        final BatesProcess process = makeProcess(in);

        final double t = in.getDouble("t");
        final JSONArray xa = in.getJSONArray("x");
        final Array x = new Array(new double[] { xa.getDouble(0), xa.getDouble(1) });
        final Array drift = process.drift(t, x);

        final JSONObject exp = (JSONObject) c.expectedRaw();
        final JSONArray dExp = exp.getJSONArray("drift");

        assertDoubleTight(name + ".drift[0]", dExp.getDouble(0), drift.get(0));
        assertDoubleTight(name + ".drift[1]", dExp.getDouble(1), drift.get(1));
        // Accessor checks (tight).
        assertDoubleTight(name + ".lambda",  exp.getDouble("lambda_acc"), process.lambda());
        assertDoubleTight(name + ".nu",      exp.getDouble("nu_acc"),     process.nu());
        assertDoubleTight(name + ".delta",   exp.getDouble("delta_acc"),  process.delta());
        assertEquals(name + ".factors",
                exp.getInt("factors"), process.factors());
    }

    private static void runEvolveCase(final String name) {
        final ReferenceReader reader = ReferenceReader.load("processes/bates_process");
        final Case c = reader.getCase(name);
        final JSONObject in = c.inputs();

        final BatesProcess process = makeProcess(in);

        final double t0 = in.getDouble("t0");
        final double dt = in.getDouble("dt");
        final JSONArray x0a = in.getJSONArray("x0");
        final JSONArray dwa = in.getJSONArray("dw");
        final Array x0 = new Array(new double[] { x0a.getDouble(0), x0a.getDouble(1) });
        final Array dw = new Array(new double[] {
                dwa.getDouble(0), dwa.getDouble(1),
                dwa.getDouble(2), dwa.getDouble(3) });

        final Array evolved = process.evolve(t0, x0, dt, dw);

        final JSONObject exp = (JSONObject) c.expectedRaw();
        final JSONArray evExp = exp.getJSONArray("evolved");
        // Bates evolve composes Heston FullTruncation evolve (closed-form
        // Math.exp/Math.sqrt) with InverseCumulativePoisson and a jump-size
        // term (Math.exp). The Poisson inverse is bit-faithful for the
        // tiny lambda*dt regime; for larger jumps the cumulative Math.exp
        // chain accumulates A13 1-ULP drift. TIGHT works here per the
        // reference parameters.
        assertDoubleTight(name + ".evolved[0]", evExp.getDouble(0), evolved.get(0));
        assertDoubleTight(name + ".evolved[1]", evExp.getDouble(1), evolved.get(1));
    }

    private static void assertDoubleTight(final String label, final double exp, final double got) {
        if (!Tolerance.tight(got, exp)) {
            fail(label + ": exp=" + exp + " got=" + got + " Δ=" + Math.abs(exp - got));
        }
        assertEquals(label, exp, got, Math.abs(exp) * 1.0e-12 + 1.0e-14);
    }
}
