/*
 Copyright (C) 2026 JQuantLib migration contributors.

 Cross-validated tests for the 7 gap stochastic-process classes ported in
 port(processes): BlackScholesProcess, BlackProcess, GarmanKohlagenProcess,
 EndEulerDiscretization, G2Process, G2ForwardProcess, JointStochasticProcess
 (incl. its inner CachingKey). Reference values from
 migration-harness/references/processes/gap_processes.json, generated by
 gap_processes_probe against QuantLib v1.42.1.
*/
package org.jquantlib.testsuite.processes;

import java.util.ArrayList;
import java.util.List;

import org.jquantlib.Settings;
import org.jquantlib.daycounters.Actual365Fixed;
import org.jquantlib.math.matrixutilities.Array;
import org.jquantlib.math.matrixutilities.Matrix;
import org.jquantlib.processes.BlackProcess;
import org.jquantlib.processes.BlackScholesMertonProcess;
import org.jquantlib.processes.BlackScholesProcess;
import org.jquantlib.processes.EndEulerDiscretization;
import org.jquantlib.processes.EulerDiscretization;
import org.jquantlib.processes.G2ForwardProcess;
import org.jquantlib.processes.G2Process;
import org.jquantlib.processes.GarmanKohlagenProcess;
import org.jquantlib.processes.GeneralizedBlackScholesProcess;
import org.jquantlib.processes.GeometricBrownianMotionProcess;
import org.jquantlib.processes.JointStochasticProcess;
import org.jquantlib.processes.StochasticProcess;
import org.jquantlib.quotes.Handle;
import org.jquantlib.quotes.Quote;
import org.jquantlib.quotes.SimpleQuote;
import org.jquantlib.termstructures.BlackVolTermStructure;
import org.jquantlib.termstructures.YieldTermStructure;
import org.jquantlib.termstructures.volatilities.BlackConstantVol;
import org.jquantlib.termstructures.yieldcurves.FlatForward;
import org.jquantlib.testsuite.util.ReferenceReader;
import org.jquantlib.testsuite.util.ReferenceReader.Case;
import org.jquantlib.testsuite.util.Tolerance;
import org.jquantlib.time.Date;
import org.jquantlib.time.Month;
import org.jquantlib.time.calendars.NullCalendar;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

/**
 * Probe-driven cross-validation for the seven gap process classes against
 * QuantLib v1.42.1. All numerics are checked at TIGHT tier (abs 1e-14,
 * rel 1e-12); integer size/factor assertions are EXACT.
 */
public class GapProcessesTest {

    private static final String REF_GROUP = "processes/gap_processes";

    private static final Date TODAY = new Date(22, Month.April, 2026);

    private static ReferenceReader ref() {
        new Settings().setEvaluationDate(TODAY);
        return ReferenceReader.load(REF_GROUP);
    }

    private static Handle<YieldTermStructure> flatCurve(final double rate) {
        return new Handle<YieldTermStructure>(
                new FlatForward(TODAY, rate, new Actual365Fixed()));
    }

    private static Handle<BlackVolTermStructure> flatVol(final double vol) {
        return new Handle<BlackVolTermStructure>(
                new BlackConstantVol(TODAY, new NullCalendar(), vol, new Actual365Fixed()));
    }

    private static void tight(final String label, final double exp, final double got) {
        assertTrue(String.format("%s: expected=%.17e actual=%.17e diff=%.3e",
                label, exp, got, Math.abs(got - exp)), Tolerance.tight(got, exp));
    }

    // ===================== Black-Scholes family =====================
    // Each subclass must apply its own carry convention.

    private static void runBsFamilyCase(final String name,
            final GeneralizedBlackScholesProcess proc) {
        final ReferenceReader r = ref();
        final Case c = r.getCase(name);
        final JSONObject in = c.inputs();
        final JSONObject exp = (JSONObject) c.expectedRaw();

        final double t  = in.getDouble("t");
        final double x  = in.getDouble("x");
        final double t0 = in.getDouble("t0");
        final double dt = in.getDouble("dt");
        final double dw = in.getDouble("dw");

        tight(name + ".x0",        exp.getDouble("x0"),        proc.x0());
        tight(name + ".drift",     exp.getDouble("drift"),     proc.drift(t, x));
        tight(name + ".diffusion", exp.getDouble("diffusion"), proc.diffusion(t, x));
        tight(name + ".evolve",    exp.getDouble("evolve"),    proc.evolve(t0, x, dt, dw));
    }

    @Test
    public void blackScholesProcess_noDividend() {
        final double s0 = 100.0, r = 0.05, vol = 0.20;
        runBsFamilyCase("blackscholes",
                new BlackScholesProcess(new Handle<Quote>(new SimpleQuote(s0)),
                        flatCurve(r), flatVol(vol)));
    }

    @Test
    public void blackScholesMertonProcess_withDividend() {
        final double s0 = 100.0, r = 0.05, q = 0.03, vol = 0.20;
        runBsFamilyCase("merton",
                new BlackScholesMertonProcess(new Handle<Quote>(new SimpleQuote(s0)),
                        flatCurve(q), flatCurve(r), flatVol(vol)));
    }

    @Test
    public void blackProcess_zeroCostOfCarry() {
        final double s0 = 100.0, r = 0.05, vol = 0.20;
        runBsFamilyCase("black",
                new BlackProcess(new Handle<Quote>(new SimpleQuote(s0)),
                        flatCurve(r), flatVol(vol)));
    }

    @Test
    public void garmanKohlagenProcess_fxCarry() {
        final double s0 = 100.0, rDom = 0.05, rFor = 0.02, vol = 0.20;
        runBsFamilyCase("garmankohlagen",
                new GarmanKohlagenProcess(new Handle<Quote>(new SimpleQuote(s0)),
                        flatCurve(rFor), flatCurve(rDom), flatVol(vol)));
    }

    // ===================== EndEulerDiscretization =====================

    @Test
    public void endEulerDiscretization_matchesCpp() {
        final ReferenceReader r = ref();

        // Case 1: GBM, END vs START agree because coefficients are x-only.
        {
            final Case c = r.getCase("endeuler_gbm");
            final JSONObject in = c.inputs();
            final JSONObject exp = (JSONObject) c.expectedRaw();
            final double t0 = in.getDouble("t0"), x0 = in.getDouble("x0"), dt = in.getDouble("dt");

            final GeometricBrownianMotionProcess gbm =
                    new GeometricBrownianMotionProcess(100.0, 0.07, 0.20);
            final EulerDiscretization euler = new EulerDiscretization();
            final EndEulerDiscretization endEuler = new EndEulerDiscretization();

            tight("euler_drift",    exp.getDouble("euler_drift"),    euler.driftDiscretization(gbm, t0, x0, dt));
            tight("euler_diff",     exp.getDouble("euler_diff"),     euler.diffusionDiscretization(gbm, t0, x0, dt));
            tight("euler_var",      exp.getDouble("euler_var"),      euler.varianceDiscretization(gbm, t0, x0, dt));
            tight("endeuler_drift", exp.getDouble("endeuler_drift"), endEuler.driftDiscretization(gbm, t0, x0, dt));
            tight("endeuler_diff",  exp.getDouble("endeuler_diff"),  endEuler.diffusionDiscretization(gbm, t0, x0, dt));
            tight("endeuler_var",   exp.getDouble("endeuler_var"),   endEuler.varianceDiscretization(gbm, t0, x0, dt));
        }

        // Case 2: the discriminating identity — EndEuler evaluates the process
        // at the END point t0+dt: endeuler.drift == proc.drift(t0+dt,x0)*dt, etc.
        {
            final Case c = r.getCase("endeuler_identity");
            final JSONObject in = c.inputs();
            final JSONObject exp = (JSONObject) c.expectedRaw();
            final double t0 = in.getDouble("t0"), x0 = in.getDouble("x0"), dt = in.getDouble("dt");

            final GeometricBrownianMotionProcess gbm =
                    new GeometricBrownianMotionProcess(100.0, 0.07, 0.20);
            final EndEulerDiscretization endEuler = new EndEulerDiscretization();

            // raw process coefficients at END point
            tight("proc_drift_end", exp.getDouble("proc_drift_end"), gbm.drift(t0 + dt, x0));
            tight("proc_diff_end",  exp.getDouble("proc_diff_end"),  gbm.diffusion(t0 + dt, x0));
            // EndEuler discretized values
            tight("endeuler_drift2", exp.getDouble("endeuler_drift"), endEuler.driftDiscretization(gbm, t0, x0, dt));
            tight("endeuler_diff2",  exp.getDouble("endeuler_diff"),  endEuler.diffusionDiscretization(gbm, t0, x0, dt));
            tight("endeuler_var2",   exp.getDouble("endeuler_var"),   endEuler.varianceDiscretization(gbm, t0, x0, dt));

            // and prove the END-point wiring directly in Java
            tight("endeuler_drift_id", gbm.drift(t0 + dt, x0) * dt,
                    endEuler.driftDiscretization(gbm, t0, x0, dt));
        }
    }

    // ===================== G2Process =====================

    @Test
    public void g2Process_matchesCpp() {
        final ReferenceReader r = ref();
        final Case c = r.getCase("g2");
        final JSONObject in = c.inputs();
        final JSONObject exp = (JSONObject) c.expectedRaw();

        final double a = in.getDouble("a"), sigma = in.getDouble("sigma");
        final double b = in.getDouble("b"), eta = in.getDouble("eta"), rho = in.getDouble("rho");
        final double t = in.getDouble("t"), t0 = in.getDouble("t0"), dt = in.getDouble("dt");
        final JSONArray xa = in.getJSONArray("x");
        final Array x = new Array(new double[] { xa.getDouble(0), xa.getDouble(1) });

        final G2Process g2 = new G2Process(a, sigma, b, eta, rho);

        assertEquals("g2.size", exp.getInt("size"), g2.size());
        tight("g2.x0",    exp.getDouble("x0"),    g2.x0());
        tight("g2.y0",    exp.getDouble("y0"),    g2.y0());
        tight("g2.a",     exp.getDouble("a_acc"),     g2.a());
        tight("g2.sigma", exp.getDouble("sigma_acc"), g2.sigma());
        tight("g2.b",     exp.getDouble("b_acc"),     g2.b());
        tight("g2.eta",   exp.getDouble("eta_acc"),   g2.eta());
        tight("g2.rho",   exp.getDouble("rho_acc"),   g2.rho());

        assertArrayTight("g2.initialValues", exp.getJSONArray("initialValues"), g2.initialValues());
        assertArrayTight("g2.drift", exp.getJSONArray("drift"), g2.drift(t, x));
        assertMatrix2x2Tight("g2.diffusion", exp.getJSONArray("diffusion"), g2.diffusion(t, x));
        assertArrayTight("g2.expectation", exp.getJSONArray("expectation"), g2.expectation(t0, x, dt));
        assertMatrix2x2Tight("g2.stdDeviation", exp.getJSONArray("stdDeviation"), g2.stdDeviation(t0, x, dt));
        assertMatrix2x2Tight("g2.covariance", exp.getJSONArray("covariance"), g2.covariance(t0, x, dt));
    }

    // ===================== G2ForwardProcess =====================

    @Test
    public void g2ForwardProcess_matchesCpp() {
        final ReferenceReader r = ref();
        final Case c = r.getCase("g2forward");
        final JSONObject in = c.inputs();
        final JSONObject exp = (JSONObject) c.expectedRaw();

        final double a = in.getDouble("a"), sigma = in.getDouble("sigma");
        final double b = in.getDouble("b"), eta = in.getDouble("eta"), rho = in.getDouble("rho");
        final double T = in.getDouble("T");
        final double t = in.getDouble("t"), t0 = in.getDouble("t0"), dt = in.getDouble("dt");
        final JSONArray xa = in.getJSONArray("x");
        final Array x = new Array(new double[] { xa.getDouble(0), xa.getDouble(1) });

        final G2ForwardProcess g2f = new G2ForwardProcess(a, sigma, b, eta, rho);
        g2f.setForwardMeasureTime(T);

        assertEquals("g2f.size", exp.getInt("size"), g2f.size());
        assertArrayTight("g2f.initialValues", exp.getJSONArray("initialValues"), g2f.initialValues());
        assertArrayTight("g2f.drift", exp.getJSONArray("drift"), g2f.drift(t, x));
        assertMatrix2x2Tight("g2f.diffusion", exp.getJSONArray("diffusion"), g2f.diffusion(t, x));
        assertArrayTight("g2f.expectation", exp.getJSONArray("expectation"), g2f.expectation(t0, x, dt));
        assertMatrix2x2Tight("g2f.stdDeviation", exp.getJSONArray("stdDeviation"), g2f.stdDeviation(t0, x, dt));
        assertMatrix2x2Tight("g2f.covariance", exp.getJSONArray("covariance"), g2f.covariance(t0, x, dt));
    }

    // ===================== JointStochasticProcess =====================

    /**
     * Minimal concrete JointStochasticProcess matching the probe's
     * TestJointProcess: zero cross-model correlation, state-independent,
     * identity numeraire, trivial pre/postEvolve.
     */
    private static final class TestJointProcess extends JointStochasticProcess {
        TestJointProcess(final List<StochasticProcess> l) {
            super(l);
        }

        @Override
        public void preEvolve(final double t0, final Array x0, final double dt, final Array dw) {
            // no-op
        }

        @Override
        public Array postEvolve(final double t0, final Array x0, final double dt,
                final Array dw, final Array y0) {
            return y0;
        }

        @Override
        public double numeraire(final double t, final Array x) {
            return 1.0;
        }

        @Override
        public boolean correlationIsStateDependent() {
            return false;
        }

        @Override
        public Matrix crossModelCorrelation(final double t0, final Array x0) {
            return new Matrix(size(), size()); // zero matrix
        }
    }

    /**
     * Like {@link TestJointProcess} but with a NON-ZERO off-diagonal cross-model
     * correlation, so the joint covariance is genuinely non-diagonal. This makes
     * the {@code diffusion()}/{@code stdDeviation()} pseudoSqrt path observable:
     * with the C++-default {@code SalvagingAlgorithm.None} (Cholesky) the returned
     * factor is lower-triangular and differs from the Spectral factor.
     */
    private static final class TestCorrelatedJointProcess extends JointStochasticProcess {
        private final double rho;

        TestCorrelatedJointProcess(final List<StochasticProcess> l, final double rho) {
            super(l);
            this.rho = rho;
        }

        @Override
        public void preEvolve(final double t0, final Array x0, final double dt, final Array dw) {
            // no-op
        }

        @Override
        public Array postEvolve(final double t0, final Array x0, final double dt,
                final Array dw, final Array y0) {
            return y0;
        }

        @Override
        public double numeraire(final double t, final Array x) {
            return 1.0;
        }

        @Override
        public boolean correlationIsStateDependent() {
            return false;
        }

        @Override
        public Matrix crossModelCorrelation(final double t0, final Array x0) {
            final Matrix m = new Matrix(size(), size()); // zero, including the diagonal
            m.set(0, 1, rho);
            m.set(1, 0, rho);
            return m;
        }
    }

    /**
     * Cross-validate the {@code diffusion()}/{@code stdDeviation()} matrix-square-root
     * path for a CORRELATED joint process. The covariance is non-diagonal, so the
     * C++-default {@code None} (Cholesky) factor (lower-triangular) is distinct from
     * the {@code Spectral} factor — this is exactly the path that was previously wrong.
     */
    @Test
    public void jointStochasticProcess_twoGbm_correlated() {
        final ReferenceReader r = ref();
        final Case c = r.getCase("joint_two_gbm_correlated");
        final JSONObject in = c.inputs();
        final JSONObject exp = (JSONObject) c.expectedRaw();

        final double rho = in.getDouble("rho");
        final double t   = in.getDouble("t");
        final double t0  = in.getDouble("t0");
        final double dt  = in.getDouble("dt");
        final JSONArray xa = in.getJSONArray("x");
        final Array x = new Array(new double[] { xa.getDouble(0), xa.getDouble(1) });

        final List<StochasticProcess> l = new ArrayList<>();
        l.add(new GeometricBrownianMotionProcess(100.0, 0.05, 0.20));
        l.add(new GeometricBrownianMotionProcess(50.0, 0.03, 0.30));
        final TestCorrelatedJointProcess jp = new TestCorrelatedJointProcess(l, rho);

        assertEquals("jpc.size",    exp.getInt("size"),    jp.size());
        assertEquals("jpc.factors", exp.getInt("factors"), jp.factors());

        final Array x0 = new Array(new double[] { 100.0, 50.0 });

        // covariance must be genuinely non-diagonal here.
        assertMatrix2x2Tight("jpc.covariance", exp.getJSONArray("covariance"), jp.covariance(t0, x0, dt));
        assertMatrix2x2Tight("jpc.crossModelCorrelation",
                exp.getJSONArray("crossModelCorrelation"), jp.crossModelCorrelation(t0, x0));

        // the two matrix-square-root methods under test:
        final Matrix diffusion = jp.diffusion(t, x);
        final Matrix stdDev = jp.stdDeviation(t0, x0, dt);
        assertMatrix2x2Tight("jpc.diffusion", exp.getJSONArray("diffusion"), diffusion);
        assertMatrix2x2Tight("jpc.stdDeviation", exp.getJSONArray("stdDeviation"), stdDev);

        // sanity: the C++-default None (Cholesky) factor is lower-triangular —
        // the upper-right entry is exactly zero (Spectral would be non-zero).
        assertEquals("jpc.diffusion upper-right must be 0 (Cholesky/None signature)",
                0.0, diffusion.get(0, 1), 0.0);
        assertEquals("jpc.stdDeviation upper-right must be 0 (Cholesky/None signature)",
                0.0, stdDev.get(0, 1), 0.0);
    }

    @Test
    public void jointStochasticProcess_twoGbm() {
        final ReferenceReader r = ref();
        final Case c = r.getCase("joint_two_gbm");
        final JSONObject in = c.inputs();
        final JSONObject exp = (JSONObject) c.expectedRaw();

        final double t  = in.getDouble("t");
        final double t0 = in.getDouble("t0");
        final double dt = in.getDouble("dt");
        final JSONArray xa = in.getJSONArray("x");
        final Array x = new Array(new double[] { xa.getDouble(0), xa.getDouble(1) });

        final List<StochasticProcess> l = new ArrayList<>();
        l.add(new GeometricBrownianMotionProcess(100.0, 0.05, 0.20));
        l.add(new GeometricBrownianMotionProcess(50.0, 0.03, 0.30));
        final TestJointProcess jp = new TestJointProcess(l);

        assertEquals("jp.size",    exp.getInt("size"),    jp.size());
        assertEquals("jp.factors", exp.getInt("factors"), jp.factors());

        assertArrayTight("jp.initialValues", exp.getJSONArray("initialValues"), jp.initialValues());
        assertArrayTight("jp.drift", exp.getJSONArray("drift"), jp.drift(t, x));

        final Array x0 = new Array(new double[] { 100.0, 50.0 });
        assertMatrix2x2Tight("jp.covariance", exp.getJSONArray("covariance"), jp.covariance(t0, x0, dt));
        assertMatrix2x2Tight("jp.crossModelCorrelation",
                exp.getJSONArray("crossModelCorrelation"), jp.crossModelCorrelation(t0, x0));

        final Array dx = new Array(new double[] { 1.5, -0.5 });
        assertArrayTight("jp.apply", exp.getJSONArray("apply"), jp.apply(x0, dx));
    }

    // ===================== helpers =====================

    private static void assertArrayTight(final String label, final JSONArray exp, final Array got) {
        assertEquals(label + ".length", exp.length(), got.size());
        for (int i = 0; i < exp.length(); i++) {
            tight(label + "[" + i + "]", exp.getDouble(i), got.get(i));
        }
    }

    /** Expected is a flat row-major [m00,m01,m10,m11] array. */
    private static void assertMatrix2x2Tight(final String label, final JSONArray exp, final Matrix got) {
        assertEquals(label + ".rows", 2, got.rows());
        assertEquals(label + ".cols", 2, got.columns());
        tight(label + "[0][0]", exp.getDouble(0), got.get(0, 0));
        tight(label + "[0][1]", exp.getDouble(1), got.get(0, 1));
        tight(label + "[1][0]", exp.getDouble(2), got.get(1, 0));
        tight(label + "[1][1]", exp.getDouble(3), got.get(1, 1));
    }
}
