// migration-harness/cpp/probes/math/interpolations/lagrange_interpolation_probe.cpp
//
// Emits QuantLib::LagrangeInterpolation's value, derivative and updated-y
// value over dense query grids.
//
// WHY THIS EXISTS: C++ keeps all of the barycentric arithmetic in
// detail::LagrangeInterpolationImpl (ql/math/interpolations/
// lagrangeinterpolation.hpp:43) behind a 20-line public shell; JQuantLib
// flattens the pair into org.jquantlib.math.interpolations.LagrangeInterpolation.
// Until now the Java side was pinned only by a table copied from the upstream
// C++ *test* (itself generated by the R package pracma) plus self-consistency
// polynomial identities — nothing that had been run through C++ v1.43 itself.
//
// Three branches of the Impl need separate coverage and get it here:
//   * the barycentric quotient away from the nodes;
//   * the node-snap short circuit, `*iter - x < 10*eps*|x|`, which returns the
//     tabulated y directly — queried both exactly at a node and at a node
//     nudged by less than the epsilon window;
//   * derivative()'s coincident-node closed form, a completely different
//     expression from its generic branch.
// updatedValue(y, x) is also emitted: it re-runs the quotient against a fresh
// y vector while reusing the cached lambda weights, and a port that recomputed
// the weights would still pass a value-only test.

#include <ql/version.hpp>

#include <ql/math/array.hpp>
#include <ql/math/interpolations/lagrangeinterpolation.hpp>

#include <cmath>
#include <string>
#include <vector>

#include "common.hpp"

using namespace QuantLib;
using namespace jqml_harness;

namespace {

void addCase(ReferenceWriter& out,
             const char* key,
             const std::vector<Real>& x,
             const std::vector<Real>& y,
             const std::vector<Real>& yUpdated) {
    const Array xa(x.begin(), x.end());
    const Array ya(y.begin(), y.end());
    LagrangeInterpolation interp(xa.begin(), xa.end(), ya.begin());
    interp.update();

    const Array yu(yUpdated.begin(), yUpdated.end());

    json rows = json::array();

    // 1. dense off-node sweep across the whole span
    const Real lo = x.front(), hi = x.back();
    for (int i = 0; i <= 60; ++i) {
        const Real q = lo + (hi - lo) * i / 60.0;
        rows.push_back(json{{"x", q},
                            {"value", interp(q)},
                            {"derivative", interp.derivative(q)},
                            {"updatedValue", interp.value(yu, q)}});
    }
    // 2. exactly at each node (node-snap short circuit + derivative's
    //    coincident-node closed form)
    for (Size i = 0; i < x.size(); ++i) {
        rows.push_back(json{{"x", x[i]},
                            {"value", interp(x[i])},
                            {"derivative", interp.derivative(x[i])},
                            {"updatedValue", interp.value(yu, x[i])},
                            {"atNode", true}});
    }
    // 3. just inside the node-snap epsilon window (10*QL_EPSILON*|x|), where
    //    the short circuit still fires, and just outside it, where it does not
    for (Size i = 0; i < x.size(); ++i) {
        for (const Real mult : {2.0, 200.0}) {
            const Real q = x[i] + mult * QL_EPSILON * std::max(std::abs(x[i]), 1.0);
            if (q <= hi && q >= lo) {
                rows.push_back(json{{"x", q},
                                    {"value", interp(q)},
                                    {"updatedValue", interp.value(yu, q)},
                                    {"nearNodeMultiplier", mult}});
            }
        }
    }

    out.addCase(key, json{{"x", x}, {"y", y}, {"yUpdated", yUpdated}}, json{{"rows", rows}});
}

} // namespace

int main() {
    ReferenceWriter out("math/interpolations/lagrange_interpolation", QL_VERSION,
                        "lagrange_interpolation_probe");

    // Equidistant nodes: the classic Runge setting, where the barycentric
    // weights span many orders of magnitude and any weight-normalisation slip
    // shows up immediately.
    {
        std::vector<Real> x, y, yu;
        for (int i = 0; i <= 10; ++i) {
            // i/5.0 rather than 0.2*i: the latter is an fma candidate, and with
            // -ffp-contract=on (clang's C++ default) `-1.0 + 0.2*5` rounds ONCE
            // and lands on 5.55e-17 instead of 0. That would put a node a
            // hair off zero, and the barycentric derivative next to such a node
            // is catastrophic-cancellation territory: the emitted number would
            // then record the compiler's contraction choice, not QuantLib's
            // arithmetic. A division is not fusable, so this form is exact.
            const Real xi = -1.0 + i / 5.0;
            x.push_back(xi);
            y.push_back(1.0 / (1.0 + 25.0 * xi * xi)); // Runge function
            yu.push_back(std::sin(3.0 * xi) + 0.5 * xi);
        }
        addCase(out, "equidistant_runge_11", x, y, yu);
    }

    // Chebyshev nodes of the second kind on [-1, 1] — the well-conditioned
    // case, and the one ChebyshevInterpolation drives.
    {
        const int n = 9;
        std::vector<Real> x, y, yu;
        for (int i = n; i >= 0; --i) {
            const Real xi = std::cos(M_PI * i / n);
            x.push_back(xi);
            y.push_back(std::exp(xi) * std::cos(2.0 * xi));
            yu.push_back(xi * xi * xi - 0.3 * xi);
        }
        addCase(out, "chebyshev_10", x, y, yu);
    }

    // Non-uniform, non-symmetric, off-origin nodes: catches an implementation
    // that accidentally assumes a [-1,1] or equally-spaced abscissa.
    {
        const std::vector<Real> x{0.5, 0.9, 1.15, 2.4, 3.05, 4.8, 7.25};
        std::vector<Real> y, yu;
        for (Real xi : x) {
            y.push_back(std::log(xi) + 0.2 * xi * xi);
            yu.push_back(1.0 / xi);
        }
        addCase(out, "nonuniform_7", x, y, yu);
    }

    // Two points: the degenerate linear case.
    {
        const std::vector<Real> x{-2.0, 3.5};
        const std::vector<Real> y{1.25, -0.75};
        const std::vector<Real> yu{0.0, 4.0};
        addCase(out, "linear_2", x, y, yu);
    }

    out.write();
    return 0;
}
