/*
 Copyright (C) 2026 JQuantLib migration contributors.

 This source code is release under the BSD License.
 See LICENSE.TXT in the project root for licence terms.
 */
package org.jquantlib.testsuite.model.equity;

import static org.junit.Assert.assertEquals;

import org.jquantlib.Settings;
import org.jquantlib.daycounters.Actual365Fixed;
import org.jquantlib.daycounters.DayCounter;
import org.jquantlib.model.PiecewiseConstantParameter;
import org.jquantlib.model.equity.PiecewiseTimeDependentHestonModel;
import org.jquantlib.quotes.Handle;
import org.jquantlib.quotes.Quote;
import org.jquantlib.quotes.SimpleQuote;
import org.jquantlib.termstructures.Compounding;
import org.jquantlib.termstructures.YieldTermStructure;
import org.jquantlib.termstructures.yieldcurves.FlatForward;
import org.jquantlib.testsuite.util.ReferenceReader;
import org.jquantlib.testsuite.util.ReferenceReader.Case;
import org.jquantlib.time.Date;
import org.jquantlib.time.Frequency;
import org.jquantlib.time.Month;
import org.jquantlib.time.TimeGrid;
import org.json.JSONObject;
import org.junit.Test;

/**
 * Phase 5h.5 cross-validation for {@link PiecewiseTimeDependentHestonModel}.
 *
 * <p>Cross-validates that piecewise-constant parameter evaluation matches C++
 * v1.42.1 bit-exactly. Reference cases are generated by
 * {@code migration-harness/cpp/probes/heston-engines/
 * piecewise_time_dependent_heston_model_probe.cpp}.
 *
 * <p><strong>Tolerance tier — exact (1e-15 abs).</strong>
 * Pure parameter lookup with no math; values must match C++ bit-exactly.
 */
public class PiecewiseTimeDependentHestonModelTest {

    private static final double EXACT = 1e-15;

    @Test
    public void parametersMatchCppProbe() {
        final ReferenceReader reader = ReferenceReader.load(
                "heston-engines/piecewise_time_dependent_heston_model");

        final Date eval = new Date(15, Month.January, 2026);
        new Settings().setEvaluationDate(eval);
        final DayCounter dc = new Actual365Fixed();

        final Handle<Quote> s0 = new Handle<Quote>(new SimpleQuote(100.0));
        final YieldTermStructure flatR = new FlatForward(eval,
                new Handle<Quote>(new SimpleQuote(0.05)),
                dc, Compounding.Continuous, Frequency.Annual);
        final YieldTermStructure flatQ = new FlatForward(eval,
                new Handle<Quote>(new SimpleQuote(0.02)),
                dc, Compounding.Continuous, Frequency.Annual);

        // Time grid identical to probe.
        final double[] grid = { 0.0, 0.5, 1.0, 1.5, 2.0 };
        final java.util.List<Double> mandatory = new java.util.ArrayList<>();
        for (final double g : grid) {
            mandatory.add(g);
        }
        final TimeGrid tg = new TimeGrid(mandatory);

        final PiecewiseConstantParameter theta = new PiecewiseConstantParameter(grid);
        theta.setParam(0, 0.04);
        theta.setParam(1, 0.05);
        theta.setParam(2, 0.06);
        theta.setParam(3, 0.07);
        theta.setParam(4, 0.08);

        final PiecewiseConstantParameter kappa = new PiecewiseConstantParameter(grid);
        kappa.setParam(0, 1.0);
        kappa.setParam(1, 1.1);
        kappa.setParam(2, 1.2);
        kappa.setParam(3, 1.3);
        kappa.setParam(4, 1.4);

        final PiecewiseConstantParameter sigma = new PiecewiseConstantParameter(grid);
        sigma.setParam(0, 0.30);
        sigma.setParam(1, 0.32);
        sigma.setParam(2, 0.34);
        sigma.setParam(3, 0.36);
        sigma.setParam(4, 0.38);

        final PiecewiseConstantParameter rho = new PiecewiseConstantParameter(grid);
        rho.setParam(0, 0.20);
        rho.setParam(1, 0.22);
        rho.setParam(2, 0.24);
        rho.setParam(3, 0.26);
        rho.setParam(4, 0.28);

        final double v0 = 0.04;

        final PiecewiseTimeDependentHestonModel model = new PiecewiseTimeDependentHestonModel(
                new Handle<YieldTermStructure>(flatR),
                new Handle<YieldTermStructure>(flatQ),
                s0, v0, theta, kappa, sigma, rho, tg);

        for (final String caseName : reader.caseNames()) {
            final Case ref = reader.getCase(caseName);
            final JSONObject in  = ref.inputs();
            final JSONObject exp = (JSONObject) ref.expectedRaw();

            if ("constants".equals(caseName)) {
                assertEquals("v0", exp.getDouble("v0"), model.v0(), EXACT);
                assertEquals("s0", exp.getDouble("s0"), model.s0(), EXACT);
            } else {
                final double t = in.getDouble("t");
                assertEquals(caseName + ".theta", exp.getDouble("theta"), model.theta(t), EXACT);
                assertEquals(caseName + ".kappa", exp.getDouble("kappa"), model.kappa(t), EXACT);
                assertEquals(caseName + ".sigma", exp.getDouble("sigma"), model.sigma(t), EXACT);
                assertEquals(caseName + ".rho",   exp.getDouble("rho"),   model.rho(t),   EXACT);
            }
        }
    }
}
