/*
 Copyright (C) 2026 JQuantLib migration contributors.

 This source code is release under the BSD License.

 This file is part of JQuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://jquantlib.org/

 JQuantLib is free software: you can redistribute it and/or modify it
 under the terms of the JQuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <jquant-devel@lists.sourceforge.net>. The license is also available online at
 <http://www.jquantlib.org/index.php/LICENSE.TXT>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.

 JQuantLib is based on QuantLib. http://quantlib.org/
 When applicable, the original copyright notice follows this notice.
 */

/*
 Copyright (C) 2004 Ferdinando Ametrano
 Copyright (C) 2007 Giorgio Facchinetti
 Copyright (C) 2009-2024 multiple contributors

 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/
*/
package org.jquantlib.testsuite.math.interpolations;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

import org.jquantlib.QL;
import org.jquantlib.math.interpolations.LagrangeInterpolation;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Java port of QuantLib v1.42.1 test-suite/interpolations.cpp (Phase 5g).
 *
 * <p>The C++ file has 38 test cases — the largest in Phase 5g — covering
 * cubic spline endpoint conditions, Hyman filter, multi-spline, functor
 * adapter, Fritsch-Butland, BackwardFlat / ForwardFlat, mixed
 * linear-cubic, SABR / NoArbSABR / FlochKennedy, Kernel, BicubicSpline,
 * Richardson extrapolation, Lagrange, B-Splines, Chebyshev,
 * LaplaceInterpolation, FlatExtrapolation.
 *
 * <p><b>Existing Java coverage</b> ({@link InterpolationTest} sibling class):
 * 12 tests already cover testInterpolateWithoutUpdate (via testAsFunctor),
 * testSplineErrorOnGaussianValues, testSplineOnGaussianValues,
 * testSplineOnGenericValues, testSimmetricEndConditions,
 * testDerivativeEndConditions, testNonRestrictiveHymanFilter,
 * testMultiSpline, testAsFunctor, testBackwardFlat, testForwardFlat,
 * testSabrInterpolation. {@link FlatForwardInterpolationTest},
 * {@link LinearInterpolationTest}, {@link BackwardInterpolationTest},
 * {@link BilinearInterpolationTest} and the SABR-focused tests
 * ({@code SABRInterpolationTest}, {@code SABRInterpolationConstructionTest},
 * {@code XABRInterpolationImplTest}) provide additional coverage.
 *
 * <p>This class adds two Lagrange-interpolation tests that are not yet
 * covered (Java {@link LagrangeInterpolation} class is present but
 * untested), plus deferral markers for the C++ tests that require
 * production classes still missing in JQuantLib (BSpline,
 * ChebyshevInterpolation, LaplaceInterpolation, RichardsonExtrapolation,
 * KernelInterpolation, BicubicSpline, Fritsch-Butland,
 * FlochKennedy SABR, Mixed Linear-Cubic, NoArbSABR interpolation, and
 * the SABR transformations / single-cases tests).
 */
public class InterpolationsTest {

    public InterpolationsTest() {
        QL.info("::::: " + this.getClass().getSimpleName() + " :::::");
    }

    private static double lagrangeTestFct(final double x) {
        // C++ interpolations.cpp lines 237-239.
        return Math.abs(x) + 0.5 * x - x * x;
    }

    /**
     * Faithful port of {@code testLagrangeInterpolation} (lines 2274-2327).
     * 79-point reference table generated by R package pracma.
     */
    @Test
    public void testLagrangeInterpolation() {
        QL.info("Testing Lagrange interpolation...");

        final double[] x = { -1.0, -0.5, -0.25, 0.1, 0.4, 0.75, 0.96 };
        final double[] y = new double[x.length];
        for (int i = 0; i < x.length; i++) {
            y[i] = lagrangeTestFct(x[i]);
        }

        final LagrangeInterpolation interpl = new LagrangeInterpolation(x, y);

        // Reference results from R package pracma — C++ lines 2285-2313.
        final double[] references = {
            -0.5000000000000000, -0.5392414024347419, -0.5591485962711904,
            -0.5629199661387594, -0.5534414777017116, -0.5333043347921566,
            -0.5048221831582063, -0.4700478608272949, -0.4307896950846587,
            -0.3886273460669714, -0.3449271969711449, -0.3008572908782903,
            -0.2574018141928359, -0.2153751266968088, -0.1754353382192734,
            -0.1380974319209344, -0.1037459341938971, -0.0726471311765894,
            -0.0449608318838433, -0.0207516779521373,  0.0000000000000000,
             0.0173877793964286,  0.0315691961126723,  0.0427562482700356,
             0.0512063534145595,  0.0572137590808174,  0.0611014067405497,
             0.0632132491361394,  0.0639070209989264,  0.0635474631523613,
             0.0625000000000000,  0.0611248703983366,  0.0597717119144768,
             0.0587745984686508,  0.0584475313615655,  0.0590803836865967,
             0.0609352981268212,  0.0642435381368876,  0.0692027925097279,
             0.0759749333281079,  0.0846842273010179,  0.0954160004849021,
             0.1082157563897290,  0.1230887474699003,  0.1400000000000001,
             0.1588747923353829,  0.1795995865576031,  0.2020234135046815,
             0.2259597111862140,  0.2511886165833182,  0.2774597108334206,
             0.3044952177998833,  0.3319936560264689,  0.3596339440766487,
             0.3870799592577457,  0.4139855497299214,  0.4400000000000001,
             0.4647739498001331,  0.4879657663513030,  0.5092483700116673,
             0.5283165133097421,  0.5448945133624253,  0.5587444376778583,
             0.5696747433431296,  0.5775493695968156,  0.5822972837863635,
             0.5839224807103117,  0.5825144353453510,  0.5782590089582251,
             0.5714498086024714,  0.5625000000000000,  0.5519545738075141,
             0.5405030652677689,  0.5289927272456703,  0.5184421566492137,
             0.5100553742352614,  0.5052363578001620,  0.5056040287552059,
             0.5130076920869246
        };

        final double tol = 50.0 * Math.ulp(1.0);
        for (int i = 0; i < 79; i++) {
            final double xx = -1.0 + i * 0.025;
            final double calculated = interpl.op(xx);
            assertFalse("Lagrange returned NaN at x=" + xx, Double.isNaN(calculated));
            assertEquals("Lagrange interpolation at x=" + xx,
                    references[i], calculated, tol);
        }
    }

    /**
     * Faithful port of {@code testLagrangeInterpolationAtSupportPoint}
     * (lines 2329-2358). Verifies stability when interpolating at /
     * very near a support point.
     */
    @Test
    public void testLagrangeInterpolationAtSupportPoint() {
        QL.info("Testing Lagrange interpolation at supporting points...");

        final int n = 5;
        final double[] x = new double[n];
        final double[] y = new double[n];
        for (int i = 0; i < n; i++) {
            x[i] = (double) i / n;
            y[i] = 1.0 / (1.0 - x[i]);
        }
        final LagrangeInterpolation interpl = new LagrangeInterpolation(x, y);

        final double relTol = 5.0e-12;
        final double eps = Math.ulp(1.0);

        for (int i = 1; i < n - 1; i++) {
            for (double z = x[i] - 100.0 * eps;
                 z < x[i] + 100.0 * eps;
                 z += 2.0 * eps) {
                final double expected = 1.0 / (1.0 - x[i]);
                final double calculated = interpl.op(z);
                assertFalse("Lagrange returned NaN at z=" + z, Double.isNaN(calculated));
                assertEquals("Lagrange near support point x[" + i + "]=" + x[i],
                        expected, calculated, relTol);
            }
        }
    }

    @Test
    @Ignore("Phase 5g audit — covered by InterpolationTest.testInterpolateWithoutUpdate "
            + "(via testAsFunctor). C++ interpolations.cpp testInterpolateWithoutUpdate.")
    public void testInterpolateWithoutUpdate() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no Fritsch-Butland interpolation class. "
            + "C++ interpolations.cpp testFritschButland.")
    public void testFritschButland() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no MixedLinearCubicInterpolation. "
            + "C++ interpolations.cpp testMixedLinearCubicMatchDerivatives.")
    public void testMixedLinearCubicMatchDerivatives() { }

    @Test
    @Ignore("Phase 5g audit — Java SABRInterpolationTest covers SABR. "
            + "C++ interpolations.cpp testSabrGuess.")
    public void testSabrGuess() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no KernelInterpolation. "
            + "C++ interpolations.cpp testKernelInterpolation.")
    public void testKernelInterpolation() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no KernelInterpolation2D. "
            + "C++ interpolations.cpp testKernelInterpolation2D.")
    public void testKernelInterpolation2D() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no Bicubic spline derivatives API. "
            + "C++ interpolations.cpp testBicubicDerivatives.")
    public void testBicubicDerivatives() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no Bicubic.update() API. "
            + "C++ interpolations.cpp testBicubicUpdate.")
    public void testBicubicUpdate() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no RichardsonExtrapolation class. "
            + "C++ interpolations.cpp testRichardsonExtrapolation.")
    public void testRichardsonExtrapolation() { }

    @Test
    @Ignore("Phase 5g.5 — see testRichardsonExtrapolation. "
            + "C++ interpolations.cpp testUnknownRichardsonExtrapolation.")
    public void testUnknownRichardsonExtrapolation() { }

    @Test
    @Ignore("Phase 5g audit — covered by NoArbSabrInterpolationTest. "
            + "C++ interpolations.cpp testNoArbSabrInterpolation.")
    public void testNoArbSabrInterpolation() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no XABR transformations API. "
            + "C++ interpolations.cpp testTransformations.")
    public void testTransformations() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no FlochKennedy SABR. "
            + "C++ interpolations.cpp testFlochKennedySabrIsSmoothAroundATM "
            + "and testLeFlochKennedySabrExample.")
    public void testFlochKennedySabr() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no LagrangeInterpolation.derivative method. "
            + "C++ interpolations.cpp testLagrangeInterpolationDerivative.")
    public void testLagrangeInterpolationDerivative() { }

    @Test
    @Ignore("Phase 5g.5 — see testLagrangeInterpolationDerivative. "
            + "C++ interpolations.cpp testLagrangeInterpolationOnChebyshevPoints.")
    public void testLagrangeInterpolationOnChebyshevPoints() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no BSpline class. "
            + "C++ interpolations.cpp testBSplines.")
    public void testBSplines() { }

    @Test
    @Ignore("Phase 5g.5 — Java BackwardFlat needs single-point handling check. "
            + "C++ interpolations.cpp testBackwardFlatOnSinglePoint.")
    public void testBackwardFlatOnSinglePoint() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no ChebyshevInterpolation. "
            + "C++ interpolations.cpp testChebyshevInterpolation.")
    public void testChebyshevInterpolation() { }

    @Test
    @Ignore("Phase 5g.5 — see testChebyshevInterpolation. "
            + "C++ interpolations.cpp testChebyshevInterpolationOnNodes.")
    public void testChebyshevInterpolationOnNodes() { }

    @Test
    @Ignore("Phase 5g.5 — see testChebyshevInterpolation. "
            + "C++ interpolations.cpp testChebyshevInterpolationUpdateY.")
    public void testChebyshevInterpolationUpdateY() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no LaplaceInterpolation. "
            + "C++ interpolations.cpp testLaplaceInterpolation.")
    public void testLaplaceInterpolation() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no FlatExtrapolator2D class. "
            + "C++ interpolations.cpp testFlatExtrapolation.")
    public void testFlatExtrapolation() { }

    @Test
    @Ignore("Phase 5g.5 — Java has no SABR transformations API. "
            + "C++ interpolations.cpp testSabrSingleCases.")
    public void testSabrSingleCases() { }
}
