/*
 Copyright (C) 2026 Jose Moya

 This source code is release under the BSD License.

 This file is part of JQuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://jquantlib.org/

 JQuantLib is free software: you can redistribute it and/or modify it
 under the terms of the JQuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <jquant-devel@lists.sourceforge.net>. The license is also available online at
 <http://www.jquantlib.org/index.php/LICENSE.TXT>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.

 JQuantLib is based on QuantLib. http://quantlib.org/
 When applicable, the original copyright notice follows this notice.
 */

package org.jquantlib.testsuite.math.interpolations;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.jquantlib.QL;
import org.jquantlib.math.interpolations.LagrangeInterpolation;
import org.jquantlib.testsuite.util.ReferenceReader;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Test;

/**
 * Cross-validates {@link LagrangeInterpolation} against the
 * {@code math/interpolations/lagrange_interpolation} probe reference.
 * <p>
 * C++ keeps every line of the barycentric arithmetic in
 * {@code detail::LagrangeInterpolationImpl}
 * ({@code ql/math/interpolations/lagrangeinterpolation.hpp:43}) behind a
 * 20-line public shell; JQuantLib flattens the pair into the single class
 * {@code LagrangeInterpolation}. The pre-existing Java coverage was a table
 * copied out of the upstream C++ *test* (generated by the R package pracma)
 * plus self-consistency polynomial identities — nothing that had itself been
 * run through C++ v1.43.
 * <p>
 * Three distinct branches of the Impl are covered:
 * <ul>
 * <li>the barycentric quotient away from the nodes;</li>
 * <li>the node-snap short circuit ({@code *iter - x < 10*eps*|x|}), probed
 * exactly at each node and at nodes nudged both inside and outside the epsilon
 * window;</li>
 * <li>{@code derivative()}'s coincident-node closed form, a different
 * expression from its generic branch.</li>
 * </ul>
 * {@code value(y, x)} (C++ {@code updatedValue}) is covered too: it re-runs the
 * quotient against a fresh y vector while reusing the cached lambda weights, so
 * a port that recomputed the weights would still pass a value-only test.
 * <p>
 * Tolerance tier: tight — 1e-12 relative, 1e-14 absolute near zero. The
 * equidistant Runge case deliberately drives barycentric weights across many
 * orders of magnitude; both sides evaluate the same quotient over the same
 * doubles, so anything looser would stop detecting a weight-normalisation slip.
 *
 * @author Jose Moya
 */
public class LagrangeInterpolationCrossValidationTest {

    private static final String GROUP = "math/interpolations/lagrange_interpolation";
    private static final double REL = 1.0e-12;
    private static final double ABS = 1.0e-14;

    public LagrangeInterpolationCrossValidationTest() {
        QL.info("::::: " + this.getClass().getSimpleName() + " :::::");
    }

    private static double[] toArray(final JSONArray a) {
        final double[] out = new double[a.length()];
        for (int i = 0; i < a.length(); i++) {
            out[i] = a.getDouble(i);
        }
        return out;
    }

    private static void assertTight(final String where, final double expected, final double actual) {
        assertEquals(where, expected, actual, Math.max(ABS, REL * Math.abs(expected)));
    }

    private static void checkCase(final String caseName) {
        final ReferenceReader ref = ReferenceReader.load(GROUP);
        final ReferenceReader.Case c = ref.getCase(caseName);

        final double[] x = toArray(c.inputs().getJSONArray("x"));
        final double[] y = toArray(c.inputs().getJSONArray("y"));
        final double[] yUpdated = toArray(c.inputs().getJSONArray("yUpdated"));

        final LagrangeInterpolation interp = new LagrangeInterpolation(x, y);

        final JSONArray rows = ((JSONObject) c.expectedRaw()).getJSONArray("rows");
        assertTrue(caseName + ": probe produced no rows", rows.length() > 0);
        int nanRows = 0;
        for (int r = 0; r < rows.length(); r++) {
            final JSONObject row = rows.getJSONObject(r);
            final double q = row.getDouble("x");
            final String where = caseName + " row " + r + " x=" + q;

            if (row.isNull("value")) {
                // Upstream defect, C++ v1.43 lagrangeinterpolation.hpp:114-119:
                //     const Real eps = 10*QL_EPSILON*std::abs(x);
                //     ... if (iter != xEnd_ && *iter - x < eps) return yBegin[...];
                // The node-snap window is scaled by |x|, so at a node whose
                // abscissa is exactly 0 the window collapses to zero, the strict
                // `<` cannot fire, and evaluation falls through to the
                // barycentric quotient where (x - x_i) == 0 divides by zero.
                // C++ returns NaN (the probe writes it as JSON null).
                //
                // JQuantLib deliberately diverges here — LagrangeInterpolation
                // ._value uses `<= eps`, which is exact at a zero node — and this
                // asserts that divergence rather than hiding it: the interpolant
                // must return the tabulated ordinate.
                final int node = indexOf(x, q);
                assertTrue(where + ": C++ returned NaN at a non-node, which the "
                        + "zero-abscissa explanation does not cover", node >= 0);
                assertEquals(where + " value (upstream NaN; Java returns the node ordinate)",
                        y[node], interp.op(q, true), 0.0);
                assertEquals(where + " updatedValue (upstream NaN; Java returns the node ordinate)",
                        yUpdated[node], interp.value(yUpdated, q), 0.0);
                nanRows++;
            } else {
                assertTight(where + " value", row.getDouble("value"), interp.op(q, true));
                assertTight(where + " updatedValue", row.getDouble("updatedValue"),
                        interp.value(yUpdated, q));
            }
            if (row.has("derivative") && !row.isNull("derivative")) {
                assertTight(where + " derivative", row.getDouble("derivative"), interp.derivative(q));
            }
        }
        // Guard the guard: only the equidistant grid has a node at exactly 0,
        // and it is queried twice (dense sweep + at-node sweep). If this count
        // ever changes, the divergence above has spread and must be re-examined.
        assertEquals(caseName + ": unexpected number of upstream-NaN rows",
                "equidistant_runge_11".equals(caseName) ? 2 : 0, nanRows);
    }

    private static int indexOf(final double[] x, final double q) {
        for (int i = 0; i < x.length; i++) {
            if (x[i] == q) {
                return i;
            }
        }
        return -1;
    }

    /** Equidistant nodes on the Runge function: the ill-conditioned weight case. */
    @Test
    public void testEquidistantRunge() {
        QL.info("Testing LagrangeInterpolation on equidistant Runge nodes against C++ v1.43...");
        checkCase("equidistant_runge_11");
    }

    /** Chebyshev nodes of the second kind — the case ChebyshevInterpolation drives. */
    @Test
    public void testChebyshevNodes() {
        QL.info("Testing LagrangeInterpolation on Chebyshev nodes against C++ v1.43...");
        checkCase("chebyshev_10");
    }

    /** Non-uniform, non-symmetric, off-origin nodes. */
    @Test
    public void testNonUniformNodes() {
        QL.info("Testing LagrangeInterpolation on non-uniform nodes against C++ v1.43...");
        checkCase("nonuniform_7");
    }

    /** Two nodes — the degenerate linear case. */
    @Test
    public void testTwoNodes() {
        QL.info("Testing LagrangeInterpolation on two nodes against C++ v1.43...");
        checkCase("linear_2");
    }
}
