/*
 Copyright (C) 2026 JQuantLib migration contributors.
 Tests for BatesEngine + BatesDetJumpEngine + BatesDoubleExpEngine +
 BatesDoubleExpDetJumpEngine (Phase 5h.5-Bates).
 */
package org.jquantlib.testsuite.pricingengines.vanilla;

import org.jquantlib.Settings;
import org.jquantlib.daycounters.Actual365Fixed;
import org.jquantlib.exercise.EuropeanExercise;
import org.jquantlib.instruments.EuropeanOption;
import org.jquantlib.instruments.Option;
import org.jquantlib.instruments.PlainVanillaPayoff;
import org.jquantlib.model.equity.BatesDoubleExpModel;
import org.jquantlib.model.equity.BatesDoubleExpModel.BatesDoubleExpDetJumpModel;
import org.jquantlib.model.equity.BatesModel;
import org.jquantlib.pricingengines.PricingEngine;
import org.jquantlib.pricingengines.vanilla.BatesDetJumpEngine;
import org.jquantlib.pricingengines.vanilla.BatesDoubleExpDetJumpEngine;
import org.jquantlib.pricingengines.vanilla.BatesDoubleExpEngine;
import org.jquantlib.pricingengines.vanilla.BatesEngine;
import org.jquantlib.processes.BatesProcess;
import org.jquantlib.quotes.Handle;
import org.jquantlib.quotes.Quote;
import org.jquantlib.quotes.SimpleQuote;
import org.jquantlib.termstructures.YieldTermStructure;
import org.jquantlib.termstructures.yieldcurves.FlatForward;
import org.jquantlib.testsuite.util.ReferenceReader;
import org.jquantlib.testsuite.util.ReferenceReader.Case;
import org.jquantlib.testsuite.util.Tolerance;
import org.jquantlib.time.Date;
import org.jquantlib.time.Month;
import org.json.JSONObject;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

/**
 * Cross-validated NPV tests for the Bates engine family. Reference values
 * from {@code migration-harness/references/pricingengines/vanilla/bates_engine.json}
 * generated by {@code bates_engine_probe} against C++ v1.42.1.
 */
public class BatesEngineTest {

    @Test public void bates_black_degenerate()       { runCase("bates_black_degenerate"); }
    @Test public void bates_jump_heavy()             { runCase("bates_jump_heavy"); }
    @Test public void bates_put_otm()                { runCase("bates_put_otm"); }
    @Test public void batesDetJump_atm()             { runCase("batesDetJump_atm"); }
    @Test public void batesDoubleExp_atm()           { runCase("batesDoubleExp_atm"); }
    @Test public void batesDoubleExp_put_otm()       { runCase("batesDoubleExp_put_otm"); }
    @Test public void batesDoubleExpDetJump_atm()    { runCase("batesDoubleExpDetJump_atm"); }

    private static void runCase(final String name) {
        final ReferenceReader reader =
                ReferenceReader.load("pricingengines/vanilla/bates_engine");
        final Case c = reader.getCase(name);
        final JSONObject in = c.inputs();

        final String engineName = in.getString("engine");
        final String typeStr    = in.getString("type");
        final double strike     = in.getDouble("strike");
        final double spot       = in.getDouble("spot");
        final double r          = in.getDouble("r");
        final double q          = in.getDouble("q");
        final int    days       = in.getInt("days");
        final double v0         = in.getDouble("v0");
        final double kappa      = in.getDouble("kappa");
        final double theta      = in.getDouble("theta");
        final double sigma      = in.getDouble("sigma");
        final double rho        = in.getDouble("rho");
        final double lambda     = in.getDouble("lambda");
        final double nu         = in.getDouble("nu");
        final double delta      = in.getDouble("delta");
        final double nuUp       = in.getDouble("nuUp");
        final double nuDown     = in.getDouble("nuDown");
        final double p          = in.getDouble("p");
        final double kappaLambda = in.getDouble("kappaLambda");
        final double thetaLambda = in.getDouble("thetaLambda");
        final int    integrationOrder = in.getInt("integrationOrder");

        final Date today = new Date(22, Month.April, 2026);
        new Settings().setEvaluationDate(today);

        final YieldTermStructure rCurve = new FlatForward(today,
                new Handle<Quote>(new SimpleQuote(r)), new Actual365Fixed());
        final YieldTermStructure qCurve = new FlatForward(today,
                new Handle<Quote>(new SimpleQuote(q)), new Actual365Fixed());
        final Handle<Quote> spotH = new Handle<Quote>(new SimpleQuote(spot));

        final BatesProcess process = new BatesProcess(
                new Handle<YieldTermStructure>(rCurve),
                new Handle<YieldTermStructure>(qCurve),
                spotH, v0, kappa, theta, sigma, rho, lambda, nu, delta);
        process.update();

        final Option.Type optionType = "call".equals(typeStr) ? Option.Type.Call : Option.Type.Put;
        final PlainVanillaPayoff payoff = new PlainVanillaPayoff(optionType, strike);
        final Date exerciseDate = today.add(days);
        final EuropeanExercise exercise = new EuropeanExercise(exerciseDate);
        final EuropeanOption option = new EuropeanOption(payoff, exercise);

        final PricingEngine engine;
        if ("bates".equals(engineName)) {
            final BatesModel model = new BatesModel(process, lambda, nu, delta);
            engine = new BatesEngine(model, process, integrationOrder);
        } else if ("batesDetJump".equals(engineName)) {
            final org.jquantlib.model.equity.BatesDetJumpModel model =
                    new org.jquantlib.model.equity.BatesDetJumpModel(
                            process, lambda, nu, delta, kappaLambda, thetaLambda);
            engine = new BatesDetJumpEngine(model, process, integrationOrder);
        } else if ("batesDoubleExp".equals(engineName)) {
            final BatesDoubleExpModel model =
                    new BatesDoubleExpModel(process, lambda, nuUp, nuDown, p);
            engine = new BatesDoubleExpEngine(model, process, integrationOrder);
        } else if ("batesDoubleExpDetJump".equals(engineName)) {
            final BatesDoubleExpDetJumpModel model = new BatesDoubleExpDetJumpModel(
                    process, lambda, nuUp, nuDown, p, kappaLambda, thetaLambda);
            engine = new BatesDoubleExpDetJumpEngine(model, process, integrationOrder);
        } else {
            throw new IllegalStateException("unknown engine: " + engineName);
        }
        option.setPricingEngine(engine);

        final double npv = option.NPV();

        final JSONObject exp = (JSONObject) c.expectedRaw();
        final double expectedNpv = exp.getDouble("npv");

        // Bates engines compose Gauss-Laguerre integration of a Gatheral
        // characteristic function with a Bates exp(nu*g + delta2*g^2) jump
        // add-on. Both Java and C++ now use n=128 quadrature (probe was
        // regenerated to match Java's only-supported order); the residual
        // drift compounds A13 1-ULP-per-call transcendental error across
        // 128 integration nodes × Math.exp/Math.log/Math.sqrt — empirically
        // ~1e-12 relative on Heston-only payoff path, slightly larger after
        // Bates jump add-on. Try LOOSE (1e-8 abs/rel) first.
        if (!Tolerance.loose(npv, expectedNpv)) {
            fail(name + ".npv: exp=" + expectedNpv + " got=" + npv
                    + " Δ=" + Math.abs(expectedNpv - npv));
        }
        assertEquals(name + ".npv", expectedNpv, npv,
                Tolerance.LOOSE_ABS + Tolerance.LOOSE_REL * Math.abs(expectedNpv));
    }
}
