/*
 Copyright (C) 2026 JQuantLib migration contributors.

 This source code is release under the BSD License.
 See LICENSE.TXT in the project root for licence terms.
 */
package org.jquantlib.testsuite.pricingengines.vanilla;

import static org.junit.Assert.fail;

import org.jquantlib.Settings;
import org.jquantlib.daycounters.Actual365Fixed;
import org.jquantlib.daycounters.DayCounter;
import org.jquantlib.exercise.EuropeanExercise;
import org.jquantlib.exercise.Exercise;
import org.jquantlib.instruments.Option;
import org.jquantlib.instruments.PlainVanillaPayoff;
import org.jquantlib.instruments.VanillaOption;
import org.jquantlib.methods.finitedifferences.schemes.FdmSchemeDesc;
import org.jquantlib.pricingengines.vanilla.FdSabrVanillaEngine;
import org.jquantlib.quotes.Handle;
import org.jquantlib.quotes.Quote;
import org.jquantlib.quotes.SimpleQuote;
import org.jquantlib.termstructures.Compounding;
import org.jquantlib.termstructures.YieldTermStructure;
import org.jquantlib.termstructures.yieldcurves.FlatForward;
import org.jquantlib.testsuite.util.ReferenceReader;
import org.jquantlib.testsuite.util.Tolerance;
import org.jquantlib.time.Date;
import org.jquantlib.time.Frequency;
import org.jquantlib.time.Month;
import org.jquantlib.time.Period;
import org.jquantlib.time.TimeUnit;
import org.json.JSONObject;
import org.junit.Test;

/**
 * Phase 2m Track C fingerprint test for {@link FdSabrVanillaEngine}.
 *
 * <p>Cross-validates NPVs for a grid of SABR call/put options against
 * C++ v1.42.1 reference values generated by
 * {@code migration-harness/cpp/probes/pricingengines/vanilla/fd_sabr_vanilla_engine_probe.cpp}.
 *
 * <p><strong>Tolerance tier</strong> — LOOSE ({@code 1e-8} abs + rel).
 * The FD grid (400 f-points x 50 x-points x 50 time steps) introduces
 * discretisation error of ~1e-4 in NPV; however, the C++ and Java use
 * identical meshers and schemes so the Java–C++ difference should stay
 * much tighter than loose, with the dominant residual being JVM
 * floating-point order-of-operations differences in the ADI rollback.
 */
public class FdSabrVanillaEngineTest {

    @Test
    public void npvMatchesCpp() {
        final ReferenceReader reader = ReferenceReader.load(
                "pricingengines/vanilla/fd_sabr_vanilla_engine");

        final Date eval = new Date(15, Month.January, 2026);
        new Settings().setEvaluationDate(eval);

        final DayCounter dc = new Actual365Fixed();
        final Date maturityDate = eval.add(new Period(2, TimeUnit.Years));
        final Exercise exercise = new EuropeanExercise(maturityDate);

        int failures = 0;
        final StringBuilder sb = new StringBuilder();

        for (final String caseName : reader.caseNames()) {
            final ReferenceReader.Case ref = reader.getCase(caseName);
            final JSONObject in  = ref.inputs();
            final JSONObject exp = (JSONObject) ref.expectedRaw();

            final double f0     = in.getDouble("f0");
            final double alpha  = in.getDouble("alpha");
            final double beta   = in.getDouble("beta");
            final double nu     = in.getDouble("nu");
            final double rho    = in.getDouble("rho");
            final double strike = in.getDouble("strike");
            final double rate   = in.getDouble("rate");
            final int tGrid     = in.getInt("tGrid");
            final int fGrid     = in.getInt("fGrid");
            final int xGrid     = in.getInt("xGrid");
            final String optType = in.getString("option_type");

            final YieldTermStructure flat = new FlatForward(
                    eval, new Handle<Quote>(new SimpleQuote(rate)), dc,
                    Compounding.Continuous, Frequency.Annual);
            final Handle<YieldTermStructure> rTS =
                    new Handle<YieldTermStructure>(flat);

            final Option.Type type = "call".equals(optType)
                    ? Option.Type.Call : Option.Type.Put;
            final PlainVanillaPayoff payoff = new PlainVanillaPayoff(type, strike);
            final VanillaOption option = new VanillaOption(payoff, exercise);

            final FdSabrVanillaEngine engine = new FdSabrVanillaEngine(
                    f0, alpha, beta, nu, rho, rTS,
                    tGrid, fGrid, xGrid,
                    0, 1.0, 1e-4, FdmSchemeDesc.Hundsdorfer());
            option.setPricingEngine(engine);

            final double npv    = option.NPV();
            final double expNpv = exp.getDouble("npv");

            if (!Tolerance.loose(npv, expNpv)) {
                final double absDiff = Math.abs(npv - expNpv);
                sb.append(String.format("%n  FAIL %-55s  exp=%.10f got=%.10f diff=%.3e",
                        caseName, expNpv, npv, absDiff));
                ++failures;
            }
        }

        if (failures > 0) {
            fail("FdSabrVanillaEngine: " + failures + " case(s) exceeded loose tolerance:"
                    + sb);
        }
    }
}
