/*
 Copyright (C) 2026 JQuantLib migration contributors.

 This source code is release under the BSD License.
 See LICENSE.TXT in the project root for licence terms.
 */
package org.jquantlib.testsuite.pricingengines;

import org.jquantlib.QL;
import org.jquantlib.Settings;
import org.jquantlib.daycounters.ActualActual;
import org.jquantlib.daycounters.DayCounter;
import org.jquantlib.exercise.EuropeanExercise;
import org.jquantlib.exercise.Exercise;
import org.jquantlib.instruments.EuropeanOption;
import org.jquantlib.instruments.Option;
import org.jquantlib.instruments.PlainVanillaPayoff;
import org.jquantlib.pricingengines.PricingEngine;
import org.jquantlib.pricingengines.vanilla.JumpDiffusionEngine;
import org.jquantlib.processes.Merton76Process;
import org.jquantlib.quotes.Handle;
import org.jquantlib.quotes.Quote;
import org.jquantlib.quotes.SimpleQuote;
import org.jquantlib.termstructures.BlackVolTermStructure;
import org.jquantlib.termstructures.YieldTermStructure;
import org.jquantlib.termstructures.volatilities.BlackConstantVol;
import org.jquantlib.termstructures.yieldcurves.FlatForward;
import org.jquantlib.testsuite.util.ReferenceReader;
import org.jquantlib.time.Date;
import org.jquantlib.time.Month;
import org.jquantlib.time.calendars.NullCalendar;
import org.json.JSONObject;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Phase 5h.5-Bates-c cross-validation of {@link JumpDiffusionEngine}
 * (Merton 1976 jump-diffusion analytic engine) + {@link Merton76Process}
 * against C++ QuantLib v1.42.1 reference NPVs.
 *
 * <p>Reference data: {@code migration-harness/references/jump-diffusion/
 * jump_diffusion_engine.json} (10 cases — 3 Bates-c maturities + 7 Haug
 * 1998 grid corners). Generated by
 * {@code migration-harness/cpp/probes/jump-diffusion/jump_diffusion_engine_probe.cpp}.
 *
 * <p>Tolerance tier: TIGHT — {@code 1e-9} absolute. The Merton
 * Poisson-sum closes deterministically given matching {@code AnalyticEuropeanEngine}
 * (already cross-validated tight in earlier phases). Haug-grid loose-accuracy
 * cases ({@code relativeAccuracy = 1e-4}) deliberately permit a
 * {@code 1e-2} per-case absolute floor — the engine's own truncation
 * criterion bounds the error.
 *
 * @author Phase 5h.5-Bates-c port
 */
public class JumpDiffusionEngineCrossValidationTest {

    public JumpDiffusionEngineCrossValidationTest() {
        QL.info("::::: " + this.getClass().getSimpleName() + " :::::");
    }

    private static final Date TODAY = new Date(22, Month.April, 2026);

    private static double readDouble(final JSONObject obj, final String key) {
        return obj.getDouble(key);
    }

    private static int readInt(final JSONObject obj, final String key) {
        return obj.getInt(key);
    }

    private static Option.Type optionType(final String label) {
        return "call".equalsIgnoreCase(label) ? Option.Type.Call : Option.Type.Put;
    }

    private double computeNpv(final ReferenceReader.Case rc) {
        new Settings().setEvaluationDate(TODAY);
        final DayCounter dc = new ActualActual(ActualActual.Convention.ISDA);

        final JSONObject inputs = rc.inputs();
        final Option.Type type = optionType(inputs.getString("type"));
        final double strike = readDouble(inputs, "strike");
        final double spot   = readDouble(inputs, "spot");
        final double r      = readDouble(inputs, "r");
        final double q      = readDouble(inputs, "q");
        final double vol    = readDouble(inputs, "vol");
        final double lambda = readDouble(inputs, "lambda");
        final double meanLogJump = readDouble(inputs, "meanLogJump");
        final double jumpVol     = readDouble(inputs, "jumpVol");
        final int days   = readInt(inputs, "days");
        final double accuracy = readDouble(inputs, "relativeAccuracy");
        final int maxIter = readInt(inputs, "maxIterations");

        final YieldTermStructure rTS = new FlatForward(TODAY, r, dc);
        final YieldTermStructure qTS = new FlatForward(TODAY, q, dc);
        final Handle<Quote> spotHandle =
                new Handle<Quote>(new SimpleQuote(spot));
        final BlackVolTermStructure volTS =
                new BlackConstantVol(TODAY, new NullCalendar(), vol, dc);

        final SimpleQuote jumpIntensityQ = new SimpleQuote(lambda);
        final SimpleQuote meanLogJumpQ   = new SimpleQuote(meanLogJump);
        final SimpleQuote jumpVolQ       = new SimpleQuote(jumpVol);

        final Merton76Process process = new Merton76Process(
                spotHandle,
                new Handle<YieldTermStructure>(qTS),
                new Handle<YieldTermStructure>(rTS),
                new Handle<BlackVolTermStructure>(volTS),
                new Handle<Quote>(jumpIntensityQ),
                new Handle<Quote>(meanLogJumpQ),
                new Handle<Quote>(jumpVolQ));

        final PricingEngine engine = new JumpDiffusionEngine(process, accuracy, maxIter);

        final Date exerciseDate = TODAY.add(days);
        final Exercise exercise = new EuropeanExercise(exerciseDate);
        final EuropeanOption option = new EuropeanOption(
                new PlainVanillaPayoff(type, strike), exercise);
        option.setPricingEngine(engine);

        return option.NPV();
    }

    /**
     * Block A — testAnalyticAndMcVsJumpDiffusion fixtures (Bates-c carry-forward).
     * Put @ K=95, S0=100, r=0.10, q=0.04, v0=0.0433, lambda=2,
     * mu=-0.2, delta=0.2, accuracy=1e-10. Exercises the
     * tight-accuracy convergence regime that the BatesModelTest cross-check
     * relies on. TIGHT tier.
     */
    @Test
    public void testBatesCFixturesVsCppReference() {
        final ReferenceReader ref = ReferenceReader.load(
                "jump-diffusion/jump_diffusion_engine");

        for (final String name : ref.caseNames()) {
            if (!name.startsWith("merton_put_")) continue;

            final ReferenceReader.Case rc = ref.getCase(name);
            final double expected =
                    ((JSONObject) rc.expectedRaw()).getDouble("npv");

            final double calculated = computeNpv(rc);

            // TIGHT: 1e-9 absolute. AnalyticEuropeanEngine
            // (the inner per-Poisson-term call) is bit-exact across
            // Java / C++ for these parameters; the only residual is
            // accumulated FP noise across the ~lambda*t=2..10 terms
            // truncated at 1e-10 relative.
            final double tol = 1.0e-9;
            assertEquals(name + " NPV", expected, calculated, tol);
        }
    }

    /**
     * Block B — Haug 1998 grid sample (gamma in {0.25, 0.50, 0.75},
     * strike in {80, 100, 120}, lambda in {1, 5, 10}, t in {0.10, 0.50}).
     * The engine here uses the looser {@code relativeAccuracy = 1e-4} that
     * the public Haug fixture targets; cross-check at {@code 1e-9} confirms
     * Java + C++ truncate the Poisson sum at the same term and produce
     * bit-comparable partial sums.
     */
    @Test
    public void testHaugGridVsCppReference() {
        final ReferenceReader ref = ReferenceReader.load(
                "jump-diffusion/jump_diffusion_engine");

        for (final String name : ref.caseNames()) {
            if (!name.startsWith("haug_")) continue;

            final ReferenceReader.Case rc = ref.getCase(name);
            final double expected =
                    ((JSONObject) rc.expectedRaw()).getDouble("npv");

            final double calculated = computeNpv(rc);

            // TIGHT 1e-9 absolute: same justification as Block A —
            // the AnalyticEuropeanEngine inner call is bit-exact and
            // both sides truncate the Poisson sum identically once the
            // last contribution falls below relativeAccuracy.
            final double tol = 1.0e-9;
            assertEquals(name + " NPV", expected, calculated, tol);
        }
    }
}
