/*
 Copyright (C) 2012 Ralph Schreyer
 Copyright (C) 2012 Mateusz Kapturski
 Copyright (C) 2026 JQuantLib migration contributors.

 This file is part of JQuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://jquantlib.org/

 JQuantLib is free software: you can redistribute it and/or modify it
 under the terms of the QuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <jquant-devel@lists.sourceforge.net>. The license is also available online at
 <http://www.jquantlib.org/index.php/LICENSE.TXT>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.

 JQuantLib is based on QuantLib. http://quantlib.org/
 When applicable, the original copyright notice follows this notice.
 */
package org.jquantlib.math.optimization;

import org.jquantlib.QL;
import org.jquantlib.lang.exceptions.LibraryException;
import org.jquantlib.math.Constants;
import org.jquantlib.math.matrixutilities.Array;
import org.jquantlib.math.randomnumbers.MersenneTwisterUniformRng;

import java.util.ArrayList;
import java.util.List;

/**
 * Differential Evolution global optimizer.
 *
 * <p>Java port of v1.42.1 {@code ql/math/optimization/differentialevolution.{hpp,cpp}}
 * (Schreyer/Kapturski, 2012).
 *
 * <p>Reference: Price, K., Storn, R., 1997. <em>Differential Evolution &mdash; A
 * Simple and Efficient Heuristic for Global Optimization over Continuous Spaces</em>, Journal of Global Optimization
 * 11, 341&ndash;359.
 *
 * <p>Seven mutation strategies and three crossover types are supported, mirroring
 * the C++ enums. Configuration uses the same fluent {@code withXxx} builder style.
 *
 * <p>The pseudo-random number stream is generated by
 * {@link MersenneTwisterUniformRng}; the helper {@code nextReal()} (locally defined) reproduces the C++
 * {@code MersenneTwisterUniformRng::nextReal()} formula {@code (nextInt32() + 0.5) / 2^32}.
 *
 * <p>Phase 5e.5b-CFC-d-84 &mdash; JQuantLib migration.
 */
public class DifferentialEvolution extends OptimizationMethod {

    private final Configuration configuration_;
    private final MersenneTwisterUniformRng rng_;
    private Array upperBound_;
    private Array lowerBound_;

    //
    // private state
    //
    private Array currGenSizeWeights_;
    private Array currGenCrossover_;
    private Candidate bestMemberEver_;
    public DifferentialEvolution() {
        this(new Configuration());
    }
    public DifferentialEvolution(final Configuration configuration) {
        this.configuration_ = configuration;
        this.rng_ = new MersenneTwisterUniformRng(configuration.seed);
    }

    /**
     * Equivalent to C++ {@code std::partial_sort(begin, begin+1, end, sort_by_cost)}: put the candidate with the
     * minimum cost into slot 0; relative order of the rest is unspecified, matching the C++ contract.
     */
    private static void partialSortMinByCost(final List< Candidate > population) {
        int minIdx = 0;
        double minCost = population.get(0).cost;
        for ( int i = 1; i < population.size(); ++i ) {
            if ( population.get(i).cost < minCost ) {
                minCost = population.get(i).cost;
                minIdx = i;
            }
        }
        if ( minIdx != 0 ) {
            final Candidate tmp = population.get(0);
            population.set(0, population.get(minIdx));
            population.set(minIdx, tmp);
        }
    }

    /**
     * Snapshot copy of a candidate list (mirrors C++ vector copy-construction used to capture intermediate
     * {@code shuffledPop1/2} states).
     */
    private static List< Candidate > copyOf(final List< Candidate > src) {
        final List< Candidate > dst = new ArrayList< Candidate >(src.size());
        for ( final Candidate c : src ) {
            dst.add(c.copy());
        }
        return dst;
    }

    /** Array of size {@code n} filled with {@code v}, mirroring C++ {@code Array(n, v)}. */
    private static Array filled(final int n, final double v) {
        final double[] data = new double[n];
        for ( int i = 0; i < n; ++i ) {
            data[i] = v;
        }
        return new Array(data);
    }

    /** {@code true} iff the value is finite (not NaN, not +/-Infinity). */
    private static boolean isFiniteValue(final double v) {
        return !Double.isNaN(v) && !Double.isInfinite(v);
    }

    public Configuration configuration() {
        return configuration_;
    }

    //
    // main entry point
    //

    @Override
    public EndCriteria.Type minimize(final Problem p, final EndCriteria endCriteria) {
        final EndCriteria.Type[] ecType = { EndCriteria.Type.None };
        p.reset();

        if ( configuration().upperBound.size() == 0 ) {
            upperBound_ = p.constraint().upperBound(p.currentValue());
        } else {
            QL.require(configuration().upperBound.size() == p.currentValue().size(),
                    "wrong upper bound size in differential evolution configuration");
            upperBound_ = configuration().upperBound;
        }
        if ( configuration().lowerBound.size() == 0 ) {
            lowerBound_ = p.constraint().lowerBound(p.currentValue());
        } else {
            QL.require(configuration().lowerBound.size() == p.currentValue().size(),
                    "wrong lower bound size in differential evolution configuration");
            lowerBound_ = configuration().lowerBound;
        }

        currGenSizeWeights_ = filled(configuration().populationMembers, configuration().stepsizeWeight);
        currGenCrossover_ = filled(configuration().populationMembers, configuration().crossoverProbability);

        final List< Candidate > population = new ArrayList< Candidate >(configuration().populationMembers);
        if ( !configuration().initialPopulation.isEmpty() ) {
            for ( int i = 0; i < configuration().initialPopulation.size(); ++i ) {
                final Candidate c = new Candidate();
                c.values = configuration().initialPopulation.get(i);
                QL.require(c.values.size() == p.currentValue().size(), "wrong values size in initial population");
                c.cost = p.costFunction().value(c.values);
                population.add(c);
            }
        } else {
            for ( int i = 0; i < configuration().populationMembers; ++i ) {
                population.add(new Candidate(p.currentValue().size()));
            }
            fillInitialPopulation(population, p);
        }

        partialSortMinByCost(population);
        bestMemberEver_ = population.get(0).copy();
        double fxOld = population.get(0).cost;
        int iteration = 0;
        final int[] stationaryPointIteration = { 0 };

        // main loop - calculate consecutive emerging populations
        while ( !endCriteria.checkMaxIterations(iteration++, ecType) ) {
            calculateNextGeneration(population, p);
            partialSortMinByCost(population);
            if ( population.get(0).cost < bestMemberEver_.cost ) {
                bestMemberEver_ = population.get(0).copy();
            }
            final double fxNew = population.get(0).cost;
            if ( endCriteria.checkStationaryFunctionValue(fxOld, fxNew, stationaryPointIteration, ecType) ) {
                break;
            }
            fxOld = fxNew;
        }

        p.setCurrentValue(bestMemberEver_.values);
        p.setFunctionValue(bestMemberEver_.cost);
        return ecType[0];
    }

    //
    // strategy dispatch
    //

    private void calculateNextGeneration(final List< Candidate > population, final Problem p) {

        List< Candidate > mirrorPopulation;
        final List< Candidate > oldPopulation = copyOf(population);

        switch ( configuration().strategy ) {

        case Rand1Standard: {
            randomize(population);
            final List< Candidate > shuffledPop1 = copyOf(population);
            randomize(population);
            final List< Candidate > shuffledPop2 = copyOf(population);
            randomize(population);
            mirrorPopulation = shuffledPop1;

            for ( int popIter = 0; popIter < population.size(); popIter++ ) {
                population.get(popIter).values = population.get(popIter).values.add(
                        shuffledPop1.get(popIter).values.sub(shuffledPop2.get(popIter).values)
                                .mul(configuration().stepsizeWeight));
            }
            break;
        }

        case BestMemberWithJitter: {
            randomize(population);
            final List< Candidate > shuffledPop1 = copyOf(population);
            randomize(population);
            final int dim = population.get(0).values.size();
            final double[] jitter = new double[dim];

            for ( int popIter = 0; popIter < population.size(); popIter++ ) {
                for ( int i = 0; i < dim; ++i ) {
                    jitter[i] = nextReal();
                }
                final Array jitArr = new Array(jitter.clone()); // (0.0001 * jitter + F)
                final Array weight = jitArr.mul(0.0001).add(configuration().stepsizeWeight);
                // bestMemberEver_ + (shuffledPop1[i].values - population[i].values) * weight
                final Array delta = shuffledPop1.get(popIter).values.sub(population.get(popIter).values);
                population.get(popIter).values = bestMemberEver_.values.add(delta.mul(weight));
            }
            mirrorPopulation = new ArrayList< Candidate >(population.size());
            for ( int i = 0; i < population.size(); ++i ) {
                mirrorPopulation.add(bestMemberEver_.copy());
            }
            break;
        }

        case CurrentToBest2Diffs: {
            randomize(population);
            final List< Candidate > shuffledPop1 = copyOf(population);
            randomize(population);

            for ( int popIter = 0; popIter < population.size(); popIter++ ) {
                final Array bestDelta = bestMemberEver_.values.sub(oldPopulation.get(popIter).values)
                        .mul(configuration().stepsizeWeight);
                final Array shufDelta = population.get(popIter).values.sub(shuffledPop1.get(popIter).values)
                        .mul(configuration().stepsizeWeight);
                population.get(popIter).values = oldPopulation.get(popIter).values.add(bestDelta).add(shufDelta);
            }
            mirrorPopulation = shuffledPop1;
            break;
        }

        case Rand1DiffWithPerVectorDither: {
            randomize(population);
            final List< Candidate > shuffledPop1 = copyOf(population);
            randomize(population);
            final List< Candidate > shuffledPop2 = copyOf(population);
            randomize(population);
            mirrorPopulation = shuffledPop1;
            final int dim = population.get(0).values.size();
            final double[] fw = new double[dim];
            for ( int i = 0; i < dim; ++i ) {
                fw[i] = (1.0 - configuration().stepsizeWeight) * nextReal() + configuration().stepsizeWeight;
            }
            final Array fWeight = new Array(fw);
            for ( int popIter = 0; popIter < population.size(); popIter++ ) {
                population.get(popIter).values = population.get(popIter).values.add(
                        fWeight.mul(shuffledPop1.get(popIter).values.sub(shuffledPop2.get(popIter).values)));
            }
            break;
        }

        case Rand1DiffWithDither: {
            randomize(population);
            final List< Candidate > shuffledPop1 = copyOf(population);
            randomize(population);
            final List< Candidate > shuffledPop2 = copyOf(population);
            randomize(population);
            mirrorPopulation = shuffledPop1;
            final double fWeight = (1.0 - configuration().stepsizeWeight) * nextReal() + configuration().stepsizeWeight;
            for ( int popIter = 0; popIter < population.size(); popIter++ ) {
                population.get(popIter).values = population.get(popIter).values.add(
                        shuffledPop1.get(popIter).values.sub(shuffledPop2.get(popIter).values).mul(fWeight));
            }
            break;
        }

        case EitherOrWithOptimalRecombination: {
            randomize(population);
            final List< Candidate > shuffledPop1 = copyOf(population);
            randomize(population);
            final List< Candidate > shuffledPop2 = copyOf(population);
            randomize(population);
            mirrorPopulation = shuffledPop1;
            final double probFWeight = 0.5;
            if ( nextReal() < probFWeight ) {
                for ( int popIter = 0; popIter < population.size(); popIter++ ) {
                    population.get(popIter).values = oldPopulation.get(popIter).values.add(
                            shuffledPop1.get(popIter).values.sub(shuffledPop2.get(popIter).values)
                                    .mul(configuration().stepsizeWeight));
                }
            } else {
                final double K = 0.5 * (configuration().stepsizeWeight + 1.0);
                for ( int popIter = 0; popIter < population.size(); popIter++ ) {
                    // oldPopulation[popIter].values + K * (shuffledPop1 - shuffledPop2 - 2*population)
                    final Array term = shuffledPop1.get(popIter).values.sub(shuffledPop2.get(popIter).values)
                            .sub(population.get(popIter).values.mul(2.0));
                    population.get(popIter).values = oldPopulation.get(popIter).values.add(term.mul(K));
                }
            }
            break;
        }

        case Rand1SelfadaptiveWithRotation: {
            randomize(population);
            final List< Candidate > shuffledPop1 = copyOf(population);
            randomize(population);
            final List< Candidate > shuffledPop2 = copyOf(population);
            randomize(population);
            mirrorPopulation = shuffledPop1;

            adaptSizeWeights();

            for ( int popIter = 0; popIter < population.size(); popIter++ ) {
                if ( nextReal() < 0.1 ) {
                    population.get(popIter).values = rotateArray(bestMemberEver_.values.clone());
                } else {
                    population.get(popIter).values = bestMemberEver_.values.add(
                            shuffledPop1.get(popIter).values.sub(shuffledPop2.get(popIter).values)
                                    .mul(currGenSizeWeights_.get(popIter)));
                }
            }
            break;
        }

        default:
            throw new LibraryException("Unknown strategy (" + configuration().strategy + ")");
        }
        // crossover uses population both as mutant source and destination,
        // matching the C++ "use same population to avoid copy" idiom
        crossover(oldPopulation, population, population, mirrorPopulation, p);
    }

    //
    // crossover / mutation-probabilities / adaptation helpers
    //

    private void crossover(final List< Candidate > oldPopulation, final List< Candidate > population,
            final List< Candidate > mutantPopulation, final List< Candidate > mirrorPopulation, final Problem p) {

        if ( configuration().crossoverIsAdaptive ) {
            adaptCrossover();
        }

        final Array mutationProbabilities = getMutationProbabilities(population);

        final int dim = population.get(0).values.size();
        final List< Array > crossoverMask = new ArrayList< Array >(population.size());
        final List< Array > invCrossoverMask = new ArrayList< Array >(population.size());
        for ( int i = 0; i < population.size(); ++i ) {
            crossoverMask.add(filled(dim, 1.0));
            invCrossoverMask.add(filled(dim, 1.0));
        }
        getCrossoverMask(crossoverMask, invCrossoverMask, mutationProbabilities);

        for ( int popIter = 0; popIter < population.size(); popIter++ ) {
            // population = old * invMask + mutant * mask
            final Array vals = oldPopulation.get(popIter).values.mul(invCrossoverMask.get(popIter))
                    .add(mutantPopulation.get(popIter).values.mul(crossoverMask.get(popIter)));
            population.get(popIter).values = vals;

            // apply bounds if requested
            if ( configuration().applyBounds ) {
                for ( int memIter = 0; memIter < vals.size(); memIter++ ) {
                    final double v = vals.get(memIter);
                    if ( v > upperBound_.get(memIter) ) {
                        vals.set(memIter, upperBound_.get(memIter) + nextReal() * (
                                mirrorPopulation.get(popIter).values.get(memIter) - upperBound_.get(memIter)));
                    }
                    final double v2 = vals.get(memIter);
                    if ( v2 < lowerBound_.get(memIter) ) {
                        vals.set(memIter, lowerBound_.get(memIter) + nextReal() * (
                                mirrorPopulation.get(popIter).values.get(memIter) - lowerBound_.get(memIter)));
                    }
                }
            }
            // evaluate cost; clamp NaN/Inf/errors to QL_MAX_REAL
            double cost;
            try {
                cost = p.value(population.get(popIter).values);
            } catch ( final RuntimeException e ) {
                cost = Constants.QL_MAX_REAL;
            }
            if ( !isFiniteValue(cost) ) {
                cost = Constants.QL_MAX_REAL;
            }
            population.get(popIter).cost = cost;
        }
    }

    private void getCrossoverMask(final List< Array > crossoverMask, final List< Array > invCrossoverMask,
            final Array mutationProbabilities) {
        for ( int cmIter = 0; cmIter < crossoverMask.size(); cmIter++ ) {
            final Array cm = crossoverMask.get(cmIter);
            final Array invCm = invCrossoverMask.get(cmIter);
            for ( int memIter = 0; memIter < cm.size(); memIter++ ) {
                if ( nextReal() < mutationProbabilities.get(cmIter) ) {
                    invCm.set(memIter, 0.0);
                } else {
                    cm.set(memIter, 0.0);
                }
            }
        }
    }

    private Array getMutationProbabilities(final List< Candidate > population) {
        Array mutationProbabilities = currGenCrossover_.clone();
        final int dim = population.get(0).values.size();
        switch ( configuration().crossoverType ) {
        case Normal:
            break;
        case Binomial:
            // currGenCrossover_ * (1 - 1/N) + 1/N
            mutationProbabilities = currGenCrossover_.mul(1.0 - 1.0 / dim).add(1.0 / dim);
            break;
        case Exponential:
            for ( int coIter = 0; coIter < currGenCrossover_.size(); coIter++ ) {
                mutationProbabilities.set(coIter,
                        (1.0 - Math.pow(currGenCrossover_.get(coIter), dim)) / (dim * (1.0 - currGenCrossover_.get(
                                coIter))));
            }
            break;
        default:
            throw new LibraryException("Unknown crossover type (" + configuration().crossoverType + ")");
        }
        return mutationProbabilities;
    }

    private Array rotateArray(final Array a) {
        randomizeArray(a);
        return a;
    }

    private void adaptSizeWeights() {
        // Brest et al., 2006 — [=Fl, =Fu, =tau1]
        final double sizeWeightLowerBound = 0.1;
        final double sizeWeightUpperBound = 0.9;
        final double sizeWeightChangeProb = 0.1;
        for ( int i = 0; i < currGenSizeWeights_.size(); ++i ) {
            if ( nextReal() < sizeWeightChangeProb ) {
                currGenSizeWeights_.set(i, sizeWeightLowerBound + nextReal() * sizeWeightUpperBound);
            }
        }
    }

    private void adaptCrossover() {
        final double crossoverChangeProb = 0.1; // [=tau2]
        for ( int i = 0; i < currGenCrossover_.size(); ++i ) {
            if ( nextReal() < crossoverChangeProb ) {
                currGenCrossover_.set(i, nextReal());
            }
        }
    }

    private void fillInitialPopulation(final List< Candidate > population, final Problem p) {

        // use initial values provided by the user as the first member
        population.get(0).values = p.currentValue().clone();
        population.get(0).cost = p.costFunction().value(population.get(0).values);
        // rest is random
        final int dim = p.currentValue().size();
        for ( int j = 1; j < population.size(); ++j ) {
            for ( int i = 0; i < dim; ++i ) {
                final double l = lowerBound_.get(i);
                final double u = upperBound_.get(i);
                population.get(j).values.set(i, l + (u - l) * nextReal());
            }
            double cost = p.costFunction().value(population.get(j).values);
            if ( !isFiniteValue(cost) ) {
                cost = Constants.QL_MAX_REAL;
            }
            population.get(j).cost = cost;
        }
    }

    //
    // small utilities
    //

    /**
     * Reproduces the anonymous-namespace {@code randomize(begin, end, rng)} helper from the C++ source: a Fisher-Yates
     * shuffle from the tail down to index 1, where each {@code rng_.nextInt32() % (i+1)} draws the swap target.
     */
    private void randomize(final List< Candidate > population) {
        final int n = population.size();
        for ( int i = n - 1; i > 0; --i ) {
            final int j = (int) (rng_.nextInt32() % (long) (i + 1));
            if ( j != i ) {
                final Candidate tmp = population.get(i);
                population.set(i, population.get(j));
                population.set(j, tmp);
            }
        }
    }

    /** Variant of {@link #randomize(List)} that operates on an {@link Array}'s slots. */
    private void randomizeArray(final Array a) {
        final int n = a.size();
        for ( int i = n - 1; i > 0; --i ) {
            final int j = (int) (rng_.nextInt32() % (long) (i + 1));
            if ( j != i ) {
                final double tmp = a.get(i);
                a.set(i, a.get(j));
                a.set(j, tmp);
            }
        }
    }

    /**
     * Mirrors C++ {@code MersenneTwisterUniformRng::nextReal()}: returns a value in {@code (0, 1)} via
     * {@code (nextInt32() + 0.5) / 2^32}.
     */
    private double nextReal() {
        return (rng_.nextInt32() + 0.5) / 4294967296.0;
    }

    /** Mutation strategy. Numerically identical to C++ enum order. */
    public enum Strategy {
        Rand1Standard, BestMemberWithJitter, CurrentToBest2Diffs, Rand1DiffWithPerVectorDither, Rand1DiffWithDither,
        EitherOrWithOptimalRecombination, Rand1SelfadaptiveWithRotation
    }

    /** Crossover scheme. */
    public enum CrossoverType {
        Normal, Binomial, Exponential
    }

    /** Candidate population member: parameter vector plus current cost. */
    public static final class Candidate {
        public Array values;
        public double cost;

        public Candidate() {
            this(0);
        }

        public Candidate(final int size) {
            final double[] data = new double[size];
            this.values = new Array(data);
            this.cost = 0.0;
        }

        public Candidate copy() {
            final Candidate c = new Candidate();
            c.values = this.values.clone();
            c.cost = this.cost;
            return c;
        }
    }

    /**
     * Fluent configuration object. Defaults mirror C++ v1.42.1.
     */
    public static final class Configuration {
        public Strategy strategy = Strategy.BestMemberWithJitter;
        public CrossoverType crossoverType = CrossoverType.Normal;
        public int populationMembers = 100;
        public double stepsizeWeight = 0.2;
        public double crossoverProbability = 0.9;
        public long seed = 0L;
        public boolean applyBounds = true;
        public boolean crossoverIsAdaptive = false;
        public List< Array > initialPopulation = new ArrayList< Array >();
        public Array upperBound = new Array(0);
        public Array lowerBound = new Array(0);

        public Configuration() {
        }

        public Configuration withBounds(final boolean b) {
            this.applyBounds = b;
            return this;
        }

        public Configuration withBounds() {
            return withBounds(true);
        }

        public Configuration withCrossoverProbability(final double p) {
            QL.require(p >= 0.0 && p <= 1.0, "Crossover probability (" + p + ") must be in [0,1] range");
            this.crossoverProbability = p;
            return this;
        }

        public Configuration withPopulationMembers(final int n) {
            QL.require(n > 0, "Positive number of population members required");
            this.populationMembers = n;
            this.initialPopulation.clear();
            return this;
        }

        public Configuration withInitialPopulation(final List< Array > c) {
            this.initialPopulation = new ArrayList< Array >(c);
            this.populationMembers = c.size();
            return this;
        }

        public Configuration withUpperBound(final Array u) {
            this.upperBound = u;
            return this;
        }

        public Configuration withLowerBound(final Array l) {
            this.lowerBound = l;
            return this;
        }

        public Configuration withSeed(final long s) {
            this.seed = s;
            return this;
        }

        public Configuration withAdaptiveCrossover(final boolean b) {
            this.crossoverIsAdaptive = b;
            return this;
        }

        public Configuration withAdaptiveCrossover() {
            return withAdaptiveCrossover(true);
        }

        public Configuration withStepsizeWeight(final double w) {
            QL.ensure(w >= 0 && w <= 2.0, "Step size weight (" + w + ") must be in [0,2] range");
            this.stepsizeWeight = w;
            return this;
        }

        public Configuration withCrossoverType(final CrossoverType t) {
            this.crossoverType = t;
            return this;
        }

        public Configuration withStrategy(final Strategy s) {
            this.strategy = s;
            return this;
        }
    }
}
