// jquantlib/src/test/java/org/jquantlib/testsuite/termstructures/volatilities/gaussian1d/Gaussian1dVolTest.java
//
// Phase 2j WI-1.4 — probe-driven cross-validation of
// Gaussian1dSmileSection + Gaussian1dSwaptionVolatility.
//
// Reference oracle: migration-harness/references/termstructures/volatility/gaussian1d_vol.json
// (generated by gaussian1d_vol_probe.cpp against C++ QuantLib v1.42.1).
//
// Test scope:
//   "atm_*" — SmileSection.atmLevel() and model.swapAnnuity() (engine-independent; WI-1.4)
//   "smile_*" / "swvol_*" — vol/optionPrice (engine-dependent; deferred to WI-2; skipped here)
//
// Tier: TIGHT for atm/annuity (1e-12 relative, 1e-14 absolute near zero).
package org.jquantlib.testsuite.termstructures.volatilities.gaussian1d;

import static org.junit.Assert.fail;

import java.util.ArrayList;
import java.util.List;

import org.jquantlib.Settings;
import org.jquantlib.daycounters.Actual360;
import org.jquantlib.daycounters.Actual365Fixed;
import org.jquantlib.indexes.EuriborSwapIsdaFixA;
import org.jquantlib.indexes.SwapIndex;
import org.jquantlib.model.shortrate.onefactormodels.gaussian1d.Gaussian1dModel;
import org.jquantlib.model.shortrate.onefactormodels.gaussian1d.Gsr;
import org.jquantlib.quotes.Handle;
import org.jquantlib.termstructures.YieldTermStructure;
import org.jquantlib.termstructures.volatilities.gaussian1d.Gaussian1dSmileSection;
import org.jquantlib.testsuite.util.ReferenceReader;
import org.jquantlib.testsuite.util.Tolerance;
import org.jquantlib.termstructures.yieldcurves.FlatForward;
import org.jquantlib.time.Date;
import org.jquantlib.time.Month;
import org.jquantlib.time.Period;
import org.jquantlib.time.TimeUnit;
import org.json.JSONObject;
import org.junit.Test;

/**
 * Cross-validates the Java {@link Gaussian1dSmileSection} (and by extension
 * {@code Gaussian1dSwaptionVolatility}) against C++ QuantLib v1.42.1.
 * <p>
 * Single {@code @Test} with collect-all-failures pattern.
 * <p>
 * "atm_*" cases are engine-independent (tested here at TIGHT tier).
 * "smile_*" and "swvol_*" cases require Gaussian1dSwaptionEngine (WI-2);
 * they are counted as skipped.
 */
public class Gaussian1dVolTest {

    private static final Date EVAL_DATE = new Date(15, Month.May, 2026);

    /** Builds the standard Gsr fixture matching the C++ probe. */
    private static Gsr buildStandardGsr() {
        new Settings().setEvaluationDate(EVAL_DATE);
        final Handle<YieldTermStructure> yts = new Handle<YieldTermStructure>(
                new FlatForward(EVAL_DATE, 0.03, new Actual360()));
        final List<Date> volStepDates = new ArrayList<Date>();
        volStepDates.add(EVAL_DATE.add(new Period(1, TimeUnit.Years)));
        volStepDates.add(EVAL_DATE.add(new Period(2, TimeUnit.Years)));
        final double[] vols = new double[]{0.01, 0.012, 0.015};
        return new Gsr(yts, volStepDates, vols, 0.01);
    }

    @Test
    public void gaussian1dVol_atmAndAnnuityMatchCpp() {
        final ReferenceReader ref = ReferenceReader.load(
                "termstructures/volatility/gaussian1d_vol");

        final Gsr gsr = buildStandardGsr();
        final Handle<YieldTermStructure> yts = gsr.termStructure();

        final List<String> failures = new ArrayList<String>();
        int skipped = 0;

        for (final String name : ref.caseNames()) {
            final ReferenceReader.Case c = ref.getCase(name);
            try {
                if (name.startsWith("atm_")) {
                    // Engine-independent: atm level and annuity
                    final JSONObject in    = c.inputs();
                    final JSONObject exp   = (JSONObject) c.expectedRaw();
                    final long fixingSerial = in.getLong("expiry_serial");
                    final int  tenorYears   = in.getInt("tenor_years");

                    final Date fixing = new Date(fixingSerial);
                    final SwapIndex si = new EuriborSwapIsdaFixA(
                            new Period(tenorYears, TimeUnit.Years), yts);

                    // Build SmileSection without engine
                    final Gaussian1dSmileSection smile = new Gaussian1dSmileSection(
                            fixing, si, gsr, new Actual365Fixed());

                    final double javaAtm     = smile.atmLevel();
                    final double javaAnnuity = smile.annuity();
                    final double cppAtm      = exp.getDouble("atm");
                    final double cppAnnuity  = exp.getDouble("annuity");

                    assertTight(failures, name + ".atm",     javaAtm,     cppAtm);
                    assertTight(failures, name + ".annuity", javaAnnuity, cppAnnuity);

                } else if (name.startsWith("smile_") || name.startsWith("swvol_")) {
                    // Engine-dependent: requires Gaussian1dSwaptionEngine (WI-2)
                    skipped++;
                } else {
                    failures.add(name + ": no dispatcher branch");
                }
            } catch (final RuntimeException ex) {
                failures.add(name + ": exception " + ex.getClass().getSimpleName()
                        + ": " + ex.getMessage());
            }
        }

        if (!failures.isEmpty()) {
            fail("Gaussian1dVolTest: " + failures.size() + " mismatch(es) "
                    + "(" + skipped + " engine-dependent cases deferred to WI-2)\n  "
                    + String.join("\n  ", failures.subList(0, Math.min(30, failures.size())))
                    + (failures.size() > 30
                            ? "\n  ... (" + (failures.size() - 30) + " more)" : ""));
        }
        // Log how many cases were deferred (informational)
        if (skipped > 0) {
            System.out.println("Gaussian1dVolTest: " + skipped
                    + " smile_*/swvol_* cases deferred to WI-2 (require Gaussian1dSwaptionEngine).");
        }
    }

    private static void assertTight(final List<String> failures, final String name,
                                    final double java, final double cpp) {
        if (!Tolerance.tight(java, cpp)) {
            failures.add(name + ": TIGHT mismatch java=" + java + " cpp=" + cpp
                    + " (diff=" + Math.abs(java - cpp) + ")");
        }
    }
}
