/*
 Copyright (C) 2015 Peter Caspers

 This source code is release under the BSD License.

 This file is part of JQuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://jquantlib.org/

 JQuantLib is free software: you can redistribute it and/or modify it
 under the terms of the JQuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <jquant-devel@lists.sourceforge.net>. The license is also available online at
 <http://www.jquantlib.org/index.php/LICENSE.TXT>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.

 JQuantLib is based on QuantLib. http://quantlib.org/
 When applicable, the original copyright notice follows this notice.
 */

/*
 Copyright (C) 2015 Peter Caspers

 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/

 QuantLib is free software: you can redistribute it and/or modify it
 under the terms of the QuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <quantlib-dev@lists.sf.net>. The license is also available online at
 <https://www.quantlib.org/license.shtml>.
*/

package org.jquantlib.termstructures.volatilities.gaussian1d;

import org.jquantlib.daycounters.DayCounter;
import org.jquantlib.indexes.IborIndex;
import org.jquantlib.indexes.SwapIndex;
import org.jquantlib.instruments.Option;
import org.jquantlib.model.shortrate.onefactormodels.gaussian1d.Gaussian1dModel;
import org.jquantlib.pricingengines.BlackFormula;
import org.jquantlib.pricingengines.PricingEngine;
import org.jquantlib.termstructures.volatilities.SmileSection;
import org.jquantlib.time.Date;

/**
 * Smile section generated by a Gaussian 1d model.
 * <p>
 * Java port of QuantLib v1.42.1 {@code ql/termstructures/volatility/gaussian1dsmilesection.{hpp,cpp}} (commit
 * {@code 099987f0ca2c11c505dc4348cdb9ce01a598e1e5}). Phase 2j WI-1.4.
 * <p>
 * If a {@link SwapIndex} is supplied, the class prices swaptions (payer ≡ call, receiver ≡ put). If an
 * {@link IborIndex} is supplied, it prices cap/floors.
 * <p>
 * <strong>WI-1.4 scope:</strong> the constructor initialises {@code atm_} and
 * {@code annuity_} from the model's {@link Gaussian1dModel#swapRate} and {@link Gaussian1dModel#swapAnnuity}, which do
 * not require a pricing engine. The {@link #optionPrice} and {@link #volatilityImpl} hooks require a
 * {@code Gaussian1dSwaptionEngine} / {@code Gaussian1dCapFloorEngine} that is ported in WI-2; they throw
 * {@link UnsupportedOperationException} until then.
 *
 * @author Peter Caspers (C++ original)
 * @author JQuantLib contributors (Java port)
 */
public class Gaussian1dSmileSection extends SmileSection {

    // ── fields ──────────────────────────────────────────────────────────────

    /** Forward swap rate (or forward IBOR rate) at y = 0. */
    private final double atm_;

    /**
     * Swap annuity (or analogous cap/floor discount factor * dcf) at y = 0. Not exposed via C++ public API; stored for
     * {@link #optionPrice} use.
     */
    private final double annuity_;

    private final Date fixingDate_;
    private final SwapIndex swapIndex_;
    private final IborIndex iborIndex_;
    private final Gaussian1dModel model_;

    /**
     * Pricing engine — a {@code Gaussian1dSwaptionEngine} or {@code Gaussian1dCapFloorEngine}. May be {@code null} when
     * the caller only needs {@link #atmLevel()} (WI-1.4 use-case).  WI-2 will inject the concrete engine.
     */
    private final PricingEngine engine_;

    // ── constructors ─────────────────────────────────────────────────────────

    /**
     * SwapIndex-based constructor (swaption vol section).
     *
     * @param fixingDate the swaption expiry / fixing date
     * @param swapIndex  swap-rate index defining conventions and tenor
     * @param model      Gaussian 1d model (provides swapRate, swapAnnuity)
     * @param dc         day counter for the SmileSection base class
     * @param engine     Gaussian1dSwaptionEngine — may be {@code null}; if so, {@link #optionPrice} and
     *                   {@link #volatilityImpl} throw until WI-2 provides the engine
     */
    public Gaussian1dSmileSection(final Date fixingDate, final SwapIndex swapIndex, final Gaussian1dModel model,
            final DayCounter dc, final PricingEngine engine) {

        // C++: SmileSection(fixingDate, dc, model->termStructure()->referenceDate())
        super(fixingDate, dc, model.termStructure().currentLink().referenceDate());

        this.fixingDate_ = fixingDate;
        this.swapIndex_ = swapIndex;
        this.iborIndex_ = null;
        this.model_ = model;
        this.engine_ = engine;

        // Compute atm = model swapRate(fixing, tenor, null, y=0, swapIdx)
        // and annuity = model swapAnnuity(fixing, tenor, null, y=0, swapIdx)
        this.atm_ = model.swapRate(fixingDate, swapIndex.tenor(), null, 0.0, swapIndex);
        this.annuity_ = model.swapAnnuity(fixingDate, swapIndex.tenor(), null, 0.0, swapIndex);
    }

    /**
     * Convenience constructor without an engine (defers to WI-2 for pricing).
     */
    public Gaussian1dSmileSection(final Date fixingDate, final SwapIndex swapIndex, final Gaussian1dModel model,
            final DayCounter dc) {
        this(fixingDate, swapIndex, model, dc, null);
    }

    /**
     * IborIndex-based constructor (cap/floor vol section).
     *
     * @param fixingDate the caplet / fixing date
     * @param iborIndex  IBOR index defining tenor and conventions
     * @param model      Gaussian 1d model
     * @param dc         day counter
     * @param engine     Gaussian1dCapFloorEngine — may be {@code null}
     */
    public Gaussian1dSmileSection(final Date fixingDate, final IborIndex iborIndex, final Gaussian1dModel model,
            final DayCounter dc, final PricingEngine engine) {

        super(fixingDate, dc, model.termStructure().currentLink().referenceDate());

        this.fixingDate_ = fixingDate;
        this.swapIndex_ = null;
        this.iborIndex_ = iborIndex;
        this.model_ = model;
        this.engine_ = engine;

        // atm = model forward rate at fixing
        this.atm_ = model.forwardRate(fixingDate, null, 0.0, iborIndex);

        // annuity ≈ dcf * zerobond(maturity)  (simplified; mirrors C++ inline)
        // C++ uses MakeCapFloor to build a cap, then day-fraction × zerobond(maturity).
        // We replicate with a direct call: iborIndex tenor gives end date.
        final Date valueDate = iborIndex.valueDate(fixingDate);
        final Date endDate = iborIndex.fixingCalendar()
                .advance(valueDate, iborIndex.tenor(), iborIndex.businessDayConvention(), iborIndex.endOfMonth());
        final double dcf = iborIndex.dayCounter().yearFraction(valueDate, endDate);
        this.annuity_ = dcf * model.zerobond(endDate);
    }

    /**
     * Convenience IborIndex constructor without an engine.
     */
    public Gaussian1dSmileSection(final Date fixingDate, final IborIndex iborIndex, final Gaussian1dModel model,
            final DayCounter dc) {
        this(fixingDate, iborIndex, model, dc, null);
    }

    // ── SmileSection abstract methods ────────────────────────────────────────

    @Override
    public double minStrike() {
        return 0.0;   // lognormal section — strike floor is zero
    }

    @Override
    public double maxStrike() {
        return Double.MAX_VALUE;
    }

    @Override
    public double atmLevel() {
        return atm_;
    }

    /**
     * Implied lognormal volatility for the given strike.
     * <p>
     * <strong>Requires WI-2 engine.</strong>
     * Mirrors C++ {@code volatilityImpl}: prices an option at the given strike using the embedded engine, then inverts
     * via {@code blackFormulaImpliedStdDev / sqrt(exerciseTime)}.
     *
     * @throws UnsupportedOperationException if engine is null (Phase 2j WI-1.4 partial port; full implementation
     *                                       requires WI-2 swaption engine)
     */
    @Override
    protected double volatilityImpl(final double strike) {
        requireEngine("volatilityImpl");
        double vol = 0.0;
        try {
            final Option.Type type = (strike >= atm_) ? Option.Type.Call : Option.Type.Put;
            final double o = optionPrice(strike, type, 1.0);
            final double stdDev = BlackFormula.blackFormulaImpliedStdDev(type, strike, atm_, o);
            vol = stdDev / Math.sqrt(exerciseTime());
        } catch ( final Exception e ) {
            // C++ silently returns 0.0 on failure; mirror that
        }
        return vol;
    }

    // ── additional public API (mirrors C++ virtual methods on SmileSection) ──

    /**
     * Returns the option price (normalised by annuity).
     * <p>
     * <strong>Requires WI-2 engine.</strong>
     * Mirrors C++ {@code Gaussian1dSmileSection::optionPrice}: prices a swaption / cap-floor via the embedded
     * Gaussian1d engine and divides by the annuity.
     *
     * @param strike   the option strike
     * @param type     {@code Call} = payer swaption / cap; {@code Put}  = receiver swaption / floor
     * @param discount additional discount factor (C++ default = 1.0)
     * @return normalised option price
     * @throws UnsupportedOperationException if engine is null
     */
    public double optionPrice(final double strike, final Option.Type type, final double discount) {
        requireEngine("optionPrice");
        // Full implementation delegates to MakeSwaption / MakeCapFloor builder
        // + embedded engine NPV, then divides by annuity_ * discount.
        // Builders are not yet in JQuantLib; this stub is completed in WI-2.
        throw new UnsupportedOperationException(
                "Gaussian1dSmileSection.optionPrice: requires WI-2 Gaussian1d swaption/cap-floor engine.");
    }

    /** Convenience overload: discount = 1.0. */
    public double optionPrice(final double strike, final Option.Type type) {
        return optionPrice(strike, type, 1.0);
    }

    // ── package-private accessors for WI-2 (engine subclasses / tests) ──────

    /** Returns the model forward rate / swap rate (atm level). */
    public double atm() {
        return atm_;
    }

    /** Returns the swap annuity (or cap discount factor * dcf). */
    public double annuity() {
        return annuity_;
    }

    // ── private helpers ──────────────────────────────────────────────────────

    private void requireEngine(final String method) {
        if ( engine_ == null ) {
            throw new UnsupportedOperationException("Gaussian1dSmileSection." + method + ": no pricing engine set. "
                    + "Inject a Gaussian1dSwaptionEngine / Gaussian1dCapFloorEngine " + "(Phase 2j WI-2).");
        }
    }
}
