/*
 Copyright (C) 2026 JQuantLib migration contributors.

 Cross-validated tests for GFunctionFactory variants
 (Standard / ExactYield / WithShifts) against QuantLib v1.42.1
 via migration-harness/references/cashflows/g_function.json (Phase 5e.6).
*/
package org.jquantlib.testsuite.cashflows;

import java.util.ArrayList;
import java.util.List;

import org.jquantlib.QL;
import org.jquantlib.Settings;
import org.jquantlib.cashflow.CmsCoupon;
import org.jquantlib.cashflow.GFunction;
import org.jquantlib.cashflow.GFunctionFactory;
import org.jquantlib.daycounters.Actual360;
import org.jquantlib.daycounters.DayCounter;
import org.jquantlib.indexes.Euribor;
import org.jquantlib.indexes.EuriborSwapIsdaFixA;
import org.jquantlib.indexes.IborIndex;
import org.jquantlib.indexes.SwapIndex;
import org.jquantlib.quotes.Handle;
import org.jquantlib.quotes.Quote;
import org.jquantlib.quotes.SimpleQuote;
import org.jquantlib.termstructures.Compounding;
import org.jquantlib.termstructures.YieldTermStructure;
import org.jquantlib.termstructures.yieldcurves.FlatForward;
import org.jquantlib.testsuite.util.ReferenceReader;
import org.jquantlib.testsuite.util.ReferenceReader.Case;
import org.jquantlib.testsuite.util.Tolerance;
import org.jquantlib.time.BusinessDayConvention;
import org.jquantlib.time.Calendar;
import org.jquantlib.time.Date;
import org.jquantlib.time.Month;
import org.jquantlib.time.Period;
import org.jquantlib.time.TimeUnit;
import org.jquantlib.time.calendars.Target;
import org.json.JSONObject;
import org.junit.Test;

import static org.junit.Assert.fail;

/**
 * Probe-driven tests for {@link GFunctionFactory}.
 *
 * <p>Cross-validated against
 * {@code migration-harness/references/cashflows/g_function.json}
 * generated by {@code g_function_probe.cpp}.
 *
 * <p>Tier rationale: closed-form analytic G-functions and Newton-calibrated
 * shift -- TIGHT (1e-12 rel, 1e-14 abs near zero). The Newton solver is
 * exact in this configuration (smooth monotone objective with analytic
 * derivative, accuracy 1e-14, large bracket [-20,20]).
 */
public class GFunctionTest {

    public GFunctionTest() {
        QL.info("::::: " + this.getClass().getSimpleName() + " :::::");
    }

    private static final String REF_GROUP = "cashflows/g_function";

    @Test
    public void gFunctionStandard_matchesCpp() {
        final ReferenceReader ref = ReferenceReader.load(REF_GROUP);
        final List<String> mismatches = new ArrayList<>();
        for (final String name : ref.caseNames()) {
            final Case c = ref.getCase(name);
            final JSONObject inp = c.inputs();
            if (!"Standard".equals(inp.getString("variant"))) {
                continue;
            }
            final JSONObject exp = (JSONObject) c.expectedRaw();
            final int q = inp.getInt("q");
            final double delta = inp.getDouble("delta");
            final int swapLength = inp.getInt("swapLength");
            final double x = inp.getDouble("x");

            final GFunction g = GFunctionFactory.newGFunctionStandard(q, delta, swapLength);
            checkAt(name, g, x, exp, mismatches, false);
        }
        report(mismatches);
    }

    @Test
    public void gFunctionExactYield_matchesCpp() {
        // Replicate the probe's CMS coupon setup exactly.
        setupCmsCoupon();
        final ReferenceReader ref = ReferenceReader.load(REF_GROUP);
        final List<String> mismatches = new ArrayList<>();
        final GFunction g = GFunctionFactory.newGFunctionExactYield(coupon);
        for (final String name : ref.caseNames()) {
            final Case c = ref.getCase(name);
            final JSONObject inp = c.inputs();
            if (!"ExactYield".equals(inp.getString("variant"))) {
                continue;
            }
            final JSONObject exp = (JSONObject) c.expectedRaw();
            final double x = inp.getDouble("x");
            checkAt(name, g, x, exp, mismatches, false);
        }
        report(mismatches);
    }

    @Test
    public void gFunctionWithShifts_matchesCpp() {
        // Replicate the probe's CMS coupon setup exactly.
        setupCmsCoupon();
        final ReferenceReader ref = ReferenceReader.load(REF_GROUP);
        final List<String> mismatches = new ArrayList<>();

        // Group cases by mean-reversion so we instantiate G(coupon, mr) once.
        Double currentMr = null;
        GFunction g = null;
        for (final String name : ref.caseNames()) {
            final Case c = ref.getCase(name);
            final JSONObject inp = c.inputs();
            if (!"WithShifts".equals(inp.getString("variant"))) {
                continue;
            }
            final JSONObject exp = (JSONObject) c.expectedRaw();
            final double mr = inp.getDouble("meanReversion");
            if (currentMr == null || currentMr.doubleValue() != mr) {
                final Handle<Quote> meanReversion =
                        new Handle<Quote>(new SimpleQuote(mr));
                g = GFunctionFactory.newGFunctionWithShifts(coupon, meanReversion);
                currentMr = mr;
            }
            final double x = inp.getDouble("x");
            // Newton-calibrated shift slightly looser than pure analytic --
            // still TIGHT but document the rationale inline.
            checkAt(name, g, x, exp, mismatches, false);
        }
        report(mismatches);
    }

    // ---------- helpers ----------

    private CmsCoupon coupon;

    private void setupCmsCoupon() {
        // Match probe: evalDate=28-Jan-2010, TARGET, Act/360, flat 4% continuous.
        final Date evalDate = new Date(28, Month.January, 2010);
        new Settings().setEvaluationDate(evalDate);

        final Calendar calendar = new Target();
        final DayCounter dc = new Actual360();

        final Handle<YieldTermStructure> rateCurve =
                new Handle<YieldTermStructure>(
                        new FlatForward(evalDate, 0.04, dc, Compounding.Continuous));

        @SuppressWarnings("unused")
        final IborIndex euribor6m = new Euribor(new Period(6, TimeUnit.Months), rateCurve);
        final SwapIndex swapIndex =
                new EuriborSwapIsdaFixA(new Period(10, TimeUnit.Years), rateCurve);

        final Date startDate = calendar.advance(evalDate, new Period(2, TimeUnit.Years),
                BusinessDayConvention.Following);
        final Date endDate = calendar.advance(startDate, new Period(6, TimeUnit.Months),
                BusinessDayConvention.Following);
        final Date paymentDate = endDate;

        coupon = new CmsCoupon(paymentDate, 100000.0,
                startDate, endDate,
                2,                       // fixingDays
                swapIndex,
                1.0,                     // gearing
                0.0,                     // spread
                new Date(), new Date(),  // refPeriod (unused)
                dc,
                false                    // isInArrears
        );
    }

    private static void checkAt(final String name, final GFunction g,
                                final double x, final JSONObject exp,
                                final List<String> mismatches,
                                final boolean loose) {
        final double actualG = g.evaluate(x);
        final double actualG1 = g.firstDerivative(x);
        final double actualG2 = g.secondDerivative(x);
        final double expectedG = exp.getDouble("G");
        final double expectedG1 = exp.getDouble("G1");
        final double expectedG2 = exp.getDouble("G2");

        check(name + ".G", actualG, expectedG, mismatches, loose);
        check(name + ".G1", actualG1, expectedG1, mismatches, loose);
        check(name + ".G2", actualG2, expectedG2, mismatches, loose);
    }

    private static void check(final String tag, final double actual,
                              final double expected, final List<String> mismatches,
                              final boolean loose) {
        final boolean ok = loose
                ? Tolerance.loose(actual, expected)
                : Tolerance.tight(actual, expected);
        if (!ok) {
            mismatches.add(tag + ": expected=" + expected + " actual=" + actual
                    + " diff=" + Math.abs(actual - expected));
        }
    }

    private static void report(final List<String> mismatches) {
        if (!mismatches.isEmpty()) {
            fail(String.join("\n", mismatches));
        }
    }
}
